const QUESTIONS_14_16 = [
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. PC A envoie une requête au serveur B. Quelle adresse IPv4 est utilisée dans le champ de destination du paquet quand ce dernier sort de PC A ?",
    m: false,
    o: ["192.168.10.1", "192.168.10.10", "192.168.11.1", "192.168.12.16"],
    a: [3],
    e: "L'adresse IP de destination dans le paquet est toujours l'adresse IP du serveur de destination (192.168.12.16), même si la trame change à chaque saut.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle adresse MAC de destination R1 utilise-t-il pour concevoir la trame à transférer de R1 vers le serveur B ?",
    m: false,
    o: [
      "R1 laisse le champ vide et transmet les données au PC.",
      "Le paquet est encapsulé dans une trame PPP et R1 ajoute l'adresse de destination PPP à la trame.",
      "Si l'adresse MAC de destination correspondant à l'adresse IPv4 n'est pas dans le cache ARP, R1 envoie une requête ARP.",
      "R1 utilise l'adresse MAC de destination de S1.",
    ],
    a: [2],
    e: "Avant d'encapsuler le paquet dans une trame, R1 vérifie son cache ARP. Si l'entrée est absente, il envoie une requête ARP pour obtenir l'adresse MAC du prochain saut.",
  },
  {
    c: "routing",
    q: "Quels sont les deux avantages du routage statique par rapport au routage dynamique ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Le routage statique se met facilement à l'échelle avec la croissance du réseau",
      "Le routage statique utilise moins de ressources du routeur (CPU, mémoire)",
      "Le routage statique est relativement facile à configurer pour les grands réseaux",
      "Le routage statique ne demande qu'une connaissance minimale du réseau",
      "Le routage statique est plus sûr puisqu'il n'envoie pas d'annonces de routage sur le réseau",
    ],
    a: [1, 4],
    e: "Le routage statique consomme moins de ressources (pas de processus de routage dynamique) et est plus sécurisé car il ne diffuse pas d'informations de routage.",
  },
  {
    c: "routing",
    q: "Dans quel cas est-il préférable d'utiliser un protocole de routage dynamique au lieu du routage statique ?",
    m: false,
    o: [
      "Dans une entreprise où les routeurs rencontrent des problèmes de performances",
      "Pour les réseaux d'entreprise de petite taille qui ne sont pas amenés à se développer",
      "Pour un réseau souche (stub network) avec un seul point de sortie",
      "Sur un réseau où de nombreuses modifications de la topologie ont été effectuées",
    ],
    a: [3],
    e: "Le routage dynamique s'adapte automatiquement aux changements de topologie, ce qui le rend préférable dans les réseaux avec de nombreuses modifications.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle est la valeur de la distance administrative de la route permettant au routeur R1 d'atteindre l'adresse IPv6 de destination 2001:DB8:CAFE:4::A ?",
    m: false,
    o: ["110", "120", "4", "1"],
    a: [1],
    e: "La distance administrative 120 correspond au protocole RIP. OSPF = 110, EIGRP = 90, statique = 1, connecté = 0.",
  },
  {
    c: "routing",
    q: "Associez la caractéristique au type de routage correspondant. (Toutes les options ne doivent pas être utilisées.)",
    m: false,
    o: [
      "Statique=configuration manuelle, pas d'adaptation auto; Dynamique=adaptation automatique aux changements, utilise protocoles de routage",
      "Statique=adaptation automatique; Dynamique=configuration manuelle uniquement",
      "Statique=utilise OSPF/RIP; Dynamique=routes saisies manuellement par l'admin",
      "Statique=protocole de diffusion; Dynamique=routes persistantes en NVRAM",
    ],
    a: [0],
    e: "Les routes statiques sont configurées manuellement et ne s'adaptent pas. Les routes dynamiques sont apprises via des protocoles (OSPF, EIGRP, RIP) et s'adaptent aux changements.",
  },
  {
    c: "routing",
    q: "Un administrateur réseau configure l'interface Fa0/0 du routeur R1 avec la commande ip address 172.16.1.254 255.255.255.0, mais show ip route n'affiche pas le réseau connecté directement. Quelle est la cause probable ?",
    m: false,
    o: [
      "La configuration doit être d'abord enregistrée en NVRAM.",
      "Le masque de sous-réseau n'est pas valide pour l'adresse IPv4.",
      "L'interface fa0/0 n'a pas été activée avec la commande no shutdown.",
      "Aucun paquet dont le réseau de destination est 172.16.1.0 n'a encore été envoyé à R1.",
    ],
    a: [2],
    e: "Les interfaces des routeurs IOS sont désactivées par défaut. La commande no shutdown est nécessaire pour activer l'interface et afficher le réseau connecté dans la table.",
  },
  {
    c: "routing",
    q: "Un routeur a appris une route vers le réseau 172.16.32.0/19 via OSPF. Quelle commande implémente une route statique flottante de secours vers ce réseau ?",
    m: false,
    o: [
      "ip route 172.16.0.0 255.255.224.0 S0/0/0 100",
      "ip route 172.16.32.0 255.255.224.0 S0/0/0 200",
      "ip route 172.16.32.0 255.255.0.0 S0/0/0 100",
      "ip route 172.16.0.0 255.255.240.0 S0/0/0 200",
    ],
    a: [1],
    e: "La route flottante doit avoir : le même réseau/masque (172.16.32.0/255.255.224.0) et une DA supérieure à OSPF (110). DA 200 > 110, donc cette route n'est active qu'en cas d'échec OSPF.",
  },
  {
    c: "routing",
    q: "Sur quels routeurs une route statique par défaut doit-elle être configurée ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Le routeur de destination utilisé comme passerelle de dernier recours",
      "Un routeur souche connecté au reste du réseau d'entreprise ou de campus",
      "Tout routeur nécessitant une route de secours du routage dynamique pour la fiabilité",
      "Tout routeur exécutant une version IOS précédente à la version 12.0",
      "Un routeur de périphérie connecté à un fournisseur de services Internet (FAI)",
    ],
    a: [1, 4],
    e: "Les routes statiques par défaut sont configurées sur les routeurs souches (une seule sortie) et les routeurs de périphérie connectés aux FAI.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Le réseau comprend deux connexions FAI. Quel élément l'administrateur doit-il configurer pour utiliser la connexion principale (EIGRP) et éviter les recherches récursives ?",
    m: false,
    o: [
      "Créer une route statique entièrement spécifiée pointant vers Fa0/0 avec une distance administrative de 1",
      "Créer une route statique pointant vers Fa0/0 avec une distance administrative de 1",
      "Créer une route statique entièrement spécifiée pointant vers Fa0/0 avec une distance administrative de 95",
      "Créer une route statique pointant vers 10.1.1.1 avec une distance administrative de 95",
      "Créer une route statique pointant vers 10.1.1.1 avec une distance administrative de 1",
    ],
    a: [2],
    e: "Une route entièrement spécifiée (interface + next-hop) évite les recherches récursives. DA 95 < 100 (EIGRP externe) mais > 90 (EIGRP interne), servant de flottante.",
  },
  {
    c: "routing",
    q: "Quelle est la caractéristique d'une route statique flottante ?",
    m: false,
    o: [
      "Lorsqu'elle est configurée, elle crée une passerelle de dernier recours.",
      "Elle est utilisée pour fournir l'équilibrage de charge entre les routes statiques.",
      "Il s'agit simplement d'une route statique avec 0.0.0.0/0 comme destination.",
      "Elle est configurée avec une distance administrative supérieure à celle du protocole de routage dynamique d'origine.",
    ],
    a: [3],
    e: "Une route statique flottante a une DA plus élevée que la route principale. Elle n'apparaît dans la table que si la route principale disparaît.",
  },
  {
    c: "routing",
    q: "Quelle combinaison de préfixe réseau et de longueur de préfixe crée une route statique par défaut IPv6 correspondant à n'importe quelle destination ?",
    m: false,
    o: ["::/0", "::1/64", "FFFF::/128", "::/128"],
    a: [0],
    e: "::/0 est l'équivalent IPv6 de 0.0.0.0/0 en IPv4 — une route par défaut qui correspond à toutes les destinations.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle opération le routeur R2 effectue-t-il sur un paquet dont l'adresse IP de destination est 192.168.10.129 ?",
    m: false,
    o: [
      "Il envoie le paquet en sortie sur l'interface FastEthernet0/0",
      "Il abandonne le paquet",
      "Il envoie le paquet en sortie sur l'interface Serial0/0/0",
      "Il envoie le paquet en sortie sur l'interface Serial0/0/1",
    ],
    a: [3],
    e: "Le routeur effectue une recherche dans sa table de routage et utilise la correspondance la plus longue (longest prefix match) pour déterminer l'interface de sortie.",
  },
  {
    c: "routing",
    q: "Un administrateur exécute la commande : ipv6 route 2001:db8:acad:1::/32 gigabitethernet0/0 2001:db8:acad:6::1 100. Quelle distance administrative est attribuée à cette route ?",
    m: false,
    o: ["0", "1", "32", "100"],
    a: [3],
    e: "Dans la commande ipv6 route, le dernier paramètre numérique est la distance administrative. Ici, 100 est la DA attribuée à cette route statique.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Pour modifier la route vers le réseau 10.0.0.0/8 en changeant l'adresse du tronçon suivant de 172.16.40.2 en 192.168.1.2, quelles commandes sont nécessaires ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "A(config)# no network 10.0.0.0 255.0.0.0 172.16.40.2",
      "A(config)# no ip route 10.0.0.0 255.0.0.0 172.16.40.2",
      "A(config)# ip route 10.0.0.0 255.0.0.0 s0/0/0",
      "A(config)# no ip address 10.0.0.1 255.0.0.0 172.16.40.2",
      "A(config)# ip route 10.0.0.0 255.0.0.0 192.168.1.2",
    ],
    a: [1, 4],
    e: "Pour modifier une route statique : supprimer l'ancienne avec no ip route et créer la nouvelle avec le bon tronçon suivant.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle commande de route statique par défaut IPv6 permettrait à R1 d'atteindre potentiellement tous les réseaux inconnus sur Internet ?",
    m: false,
    o: [
      "R1(config)# ipv6 route 2001:db8:32::/64 G0/1 fe80::2",
      "R1(config)# ipv6 route ::/0 G0/0 fe80::2",
      "R1(config)# ipv6 route 2001:db8:32::/64 G0/0",
      "R1(config)# ipv6 route ::/0 G0/1 fe80::2",
    ],
    a: [3],
    e: "::/0 est la route par défaut IPv6. L'interface G0/1 et le tronçon suivant fe80::2 indiquent la bonne sortie vers Internet.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quel type de route statique IPv6 est configuré ?",
    m: false,
    o: [
      "Route statique entièrement spécifiée",
      "Route statique flottante",
      "Route statique connectée directement",
      "Route statique récursive",
    ],
    a: [3],
    e: "Une route statique récursive spécifie uniquement l'adresse du tronçon suivant (next-hop). Le routeur doit effectuer une recherche récursive pour trouver l'interface de sortie.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. L'ingénieur réseau souhaite utiliser la connexion FAI principale pour toutes les connexions externes et la liaison de secours uniquement en cas d'échec. Quel jeu de commandes doit être exécuté ?",
    m: false,
    o: [
      "ip route 198.133.219.24 255.255.255.252 / ip route 64.100.210.80 255.255.255.252 10",
      "ip route 0.0.0.0 0.0.0.0 s0/0/0 / ip route 0.0.0.0 0.0.0.0 s0/1/0 10",
      "ip route 0.0.0.0 0.0.0.0 s0/0/0 / ip route 0.0.0.0 0.0.0.0 s0/1/0",
      "ip route 198.133.219.24 255.255.255.252 / ip route 64.100.210.80 255.255.255.252",
    ],
    a: [1],
    e: "Une route par défaut sur s0/0/0 (DA 1 par défaut) et une route flottante sur s0/1/0 (DA 10). La seconde n'est active que si la première tombe.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. La petite entreprise utilise le routage statique. Les utilisateurs LAN du routeur R2 ont signalé un problème de connectivité. Quel est le problème ?",
    m: false,
    o: [
      "R1 doit disposer d'une route par défaut vers R2.",
      "R2 doit disposer d'une route statique vers les LAN de R1.",
      "R1 et R2 doivent utiliser un protocole de routage dynamique.",
      "R2 doit disposer d'une route statique vers Internet.",
      "R1 doit disposer d'une route statique vers le LAN de R2.",
    ],
    a: [4],
    e: "Pour que le trafic soit bidirectionnel, R1 doit avoir une route vers le réseau LAN de R2, pas seulement R2 vers R1.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Un administrateur tente de configurer une route statique IPv6 sur R1 vers le réseau de R2, mais la connectivité échoue. Quelle erreur a été commise ?",
    m: false,
    o: [
      "Le préfixe réseau est incorrect.",
      "L'interface est incorrecte.",
      "L'adresse du tronçon suivant est incorrecte.",
      "Le réseau de destination est incorrect.",
    ],
    a: [1],
    e: "Si l'interface de sortie est incorrecte dans une route statique IPv6, les paquets seront envoyés sur la mauvaise interface et ne pourront pas atteindre la destination.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle est la méthode d'installation de la route hôte 2001:DB8:CAFE:4::1/128 dans la table de routage ?",
    m: false,
    o: [
      "Cette route a été saisie manuellement par un administrateur.",
      "La route a été apprise de manière dynamique à partir d'un autre routeur.",
      "La route a été créée de manière dynamique par le routeur R1.",
      "La route a été installée automatiquement lors de la configuration d'une adresse IP sur une interface active.",
    ],
    a: [3],
    e: "Lorsqu'une adresse IPv6 est configurée sur une interface, le routeur installe automatiquement une route hôte (/128) pour cette adresse dans la table de routage.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. L'hôte HostA tente de contacter le serveur ServerB. Quels sont les deux énoncés décrivant l'adressage utilisé par HostA ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Une trame dont l'adresse MAC de destination est celle du routeur RouterA",
      "Un paquet dont l'adresse IP de destination est celle du serveur ServerB",
      "Un paquet dont l'adresse IP de destination est celle du routeur RouterB",
      "Une trame dont l'adresse MAC de destination est celle du serveur ServerB",
      "Un paquet dont l'adresse IP de destination est celle du routeur RouterA",
      "Une trame dont l'adresse MAC de destination est celle du commutateur SwitchA",
    ],
    a: [0, 1],
    e: "L'adresse IP destination du paquet est toujours ServerB. La trame est adressée au routeur (gateway) RouterA car il est sur le même réseau local que HostA.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Les tests ping de R1 à 10.1.1.2 réussissent, mais les tests vers n'importe quelle adresse du réseau 192.168.2.0 échouent. Quelle est la cause probable ?",
    m: false,
    o: [
      "La route statique de 192.168.2.0 n'est pas correctement configurée sur R1.",
      "L'interface série entre les deux routeurs est hors service.",
      "Il n'existe aucune passerelle de dernier recours sur R1.",
      "Une route par défaut n'est pas configurée sur R1.",
    ],
    a: [0],
    e: "Puisque la liaison série fonctionne (ping 10.1.1.2 OK), le problème est une route statique mal configurée pour atteindre 192.168.2.0.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Un administrateur tente de configurer une route statique par défaut sur R1, mais l'itinéraire n'apparaît pas dans la table de routage. Qu'est-ce qui l'empêche d'être installée ?",
    m: false,
    o: [
      "L'adresse du tronçon suivant est incorrecte.",
      "Le réseau de destination est incorrect.",
      "Le masque de réseau est incorrect.",
      "L'interface de sortie est manquante.",
    ],
    a: [0],
    e: "Si l'adresse du tronçon suivant est incorrecte ou inaccessible, la route statique ne peut pas être installée dans la table de routage.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. La liaison OSPF (198.51.0.4/30) devrait être la liaison principale. La commande ip route 0.0.0.0 0.0.0.0 S0/1/1 100 a été émise mais le trafic utilise la liaison de secours même quand OSPF fonctionne. Quelle modification doit être apportée ?",
    m: false,
    o: [
      "Ajoutez l'adresse du voisin de saut suivant 198.51.0.8.",
      "Remplacez le réseau de destination par 198.51.0.5.",
      "Modifiez la distance administrative à 120.",
      "Modifiez la distance administrative à 1.",
    ],
    a: [2],
    e: "OSPF a une DA de 110. La route statique avec DA 100 est préférée à OSPF. En changeant la DA à 120 (> 110), la route OSPF sera prioritaire.",
  },
  {
    c: "routing",
    q: "Quelle caractéristique complète l'énoncé suivant : « Lorsqu'une route statique IPv6 est configurée, l'installation peut être vérifiée avec… »",
    m: false,
    o: [
      "la commande show ipv6 route static",
      "la commande ipv6 unicast-routing",
      "l'adresse de saut suivant de deux routeurs adjacents différents",
      "le type d'interface et le numéro d'interface",
    ],
    a: [0],
    e: "La commande show ipv6 route static affiche uniquement les routes statiques IPv6 de la table de routage, permettant de vérifier leur installation.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 192.168.139.244 ?",
    m: false,
    o: [
      "Serial0/0/1",
      "GigabitEthernet0/0",
      "GigabitEthernet0/1",
      "Aucun, le paquet est abandonné",
    ],
    a: [1],
    e: "Le routeur effectue une recherche de correspondance la plus longue dans sa table de routage pour déterminer quelle interface utiliser pour cette adresse de destination.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle solution de routage permettra à PC A et PC B d'accéder à Internet avec une utilisation minimale du CPU et de la bande passante ?",
    m: false,
    o: [
      "Configurer une route dynamique de R1 vers Edge et une route statique de Edge vers R1.",
      "Configurer un protocole de routage dynamique entre R1 et Edge et diffuser toutes les routes.",
      "Configurer une route statique de R1 vers Edge et une route dynamique de Edge vers R1.",
      "Configurer une route statique par défaut de R1 vers Edge, une route par défaut de Edge vers Internet et une route statique de Edge vers R1.",
    ],
    a: [3],
    e: "Des routes statiques et par défaut consomment moins de ressources que les protocoles dynamiques. R1 utilise une route par défaut vers Edge, qui lui-même a une route par défaut vers Internet.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Que se passe-t-il lorsque l'administrateur saisit la nouvelle route statique vers 172.16.1.0 alors qu'une route RIP existe déjà ?",
    m: false,
    o: [
      "La route 172.16.1.0 apprise via RIP est remplacée par la route statique dans la table.",
      "La route statique 172.16.1.0 est saisie dans la configuration courante mais n'est pas affichée dans la table de routage.",
      "La route statique 172.16.1.0 est ajoutée aux routes existantes dans la table de routage.",
      "La route par défaut 0.0.0.0 est remplacée par la route statique 172.16.1.0.",
    ],
    a: [0],
    e: "Une route statique a une DA de 1, inférieure à celle de RIP (120). La route statique remplace donc la route RIP dans la table de routage.",
  },
  {
    c: "routing",
    q: "Quelles sont les informations requises dans une route statique entièrement spécifiée pour éliminer les recherches récursives ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "L'adresse IP du voisin du tronçon suivant",
      "L'ID d'interface du voisin du tronçon suivant",
      "L'ID de l'interface de sortie du routeur local",
      "L'adresse IP de l'interface de sortie du routeur local",
      "La distance administrative pour le réseau de destination",
    ],
    a: [0, 2],
    e: "Une route entièrement spécifiée contient à la fois l'interface de sortie ET l'adresse du tronçon suivant, éliminant ainsi les recherches récursives.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle commande configure correctement une route statique IPv6 sur R2 pour permettre au trafic de PC2 d'atteindre PC1 sans effectuer de recherche récursive ?",
    m: false,
    o: [
      "R2(config)# ipv6 route 2001:db8:10:12::/64 S0/0/0",
      "R2(config)# ipv6 route 2001:db8:10:12::/64 S0/0/1",
      "R2(config)# ipv6 route ::/0 2001:db8:32::1",
      "R2(config)# ipv6 route 2001:db8:10:12::/64 2001:db8:32::1",
    ],
    a: [0],
    e: "En spécifiant l'interface de sortie (S0/0/0) directement, la route est entièrement spécifiée et évite les recherches récursives.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle route statique doit-on saisir pour créer une route de secours vers le réseau 172.16.1.0 utilisée uniquement en cas de défaillance de la route RIP ?",
    m: false,
    o: [
      "ip route 172.16.1.0 255.255.255.0 s0/0/0 91",
      "ip route 172.16.1.0 255.255.255.0 s0/0/0",
      "ip route 172.16.1.0 255.255.255.0 s0/0/0 121",
      "ip route 172.16.1.0 255.255.255.0 s0/0/0 111",
    ],
    a: [2],
    e: "RIP a une DA de 120. Pour que la route statique soit flottante (de secours), sa DA doit être > 120. DA 121 > 120, donc la route statique n'est active qu'en cas d'absence de la route RIP.",
  },
  {
    c: "routing",
    q: "Un utilisateur signale que PC0 ne peut pas visiter www.server.com. Après dépannage, quelle est la cause du problème ?",
    m: false,
    o: [
      "L'adresse du serveur DNS sur PC0 est mal configurée.",
      "Le routage entre le siège social et le site distant est mal configuré.",
      "La fréquence d'horloge sur l'une des liaisons série est mal configurée.",
      "Une interface série du site distant est mal configurée.",
    ],
    a: [1],
    e: "Si le problème est de routage entre sites, les paquets ne peuvent pas atteindre le serveur web distant, même si la résolution DNS fonctionne localement.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Comment le routeur traite-t-il un paquet dont l'adresse IP de destination est 192.168.12.227 ?",
    m: false,
    o: [
      "Il envoie le paquet à l'interface GigabitEthernet0/0",
      "Il abandonne le paquet",
      "Il envoie le paquet à l'interface GigabitEthernet0/1",
      "Il envoie le paquet à l'interface Serial0/0/0",
    ],
    a: [3],
    e: "Le routeur consulte sa table de routage et utilise la correspondance la plus longue pour déterminer que le paquet doit sortir par Serial0/0/0.",
  },
  {
    c: "routing",
    q: "Qu'arrive-t-il à une entrée de route statique lorsque l'interface de sortie associée est mise hors service (shutdown) ?",
    m: false,
    o: [
      "La route statique est supprimée de la table de routage.",
      "La route statique reste dans la table car elle est définie comme statique.",
      "Le routeur redirige automatiquement la route pour utiliser une autre interface.",
      "Le routeur interroge ses voisins pour trouver une route de remplacement.",
    ],
    a: [0],
    e: "Si l'interface de sortie d'une route statique est désactivée, la route est retirée de la table de routage car elle devient inutilisable.",
  },
  {
    c: "routing",
    q: "Quelle est la caractéristique d'une route statique qui correspond à tous les paquets (route par défaut) ?",
    m: false,
    o: [
      "Elle est configurée avec une distance administrative supérieure à celle du protocole de routage dynamique.",
      "Elle sauvegarde une route déjà découverte par un protocole de routage dynamique.",
      "Elle utilise une adresse de réseau unique pour envoyer plusieurs routes statiques vers une même destination.",
      "Elle identifie l'adresse IP de la passerelle vers laquelle le routeur envoie tous les paquets IP sans route correspondante.",
    ],
    a: [3],
    e: "La route par défaut (0.0.0.0/0 en IPv4, ::/0 en IPv6) correspond à toutes les destinations et pointe vers la passerelle de dernier recours.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle route est utilisée pour transférer un paquet avec l'adresse IP source 192.168.10.1 et l'adresse de destination 10.1.1.1 ?",
    m: false,
    o: [
      "S 10.1.0.0/16 is directly connected, GigabitEthernet0/0",
      "C 192.168.10.0/30 is directly connected, GigabitEthernet0/1",
      "S* 0.0.0.0/0 [1/0] via 172.16.1.1",
      "O 10.1.1.0/24 [110/65] via 192.168.200.2",
    ],
    a: [3],
    e: "La route OSPF vers 10.1.1.0/24 est la correspondance la plus longue pour la destination 10.1.1.1. Elle est préférée à la route statique /16 qui est moins spécifique.",
  },
  {
    c: "routing",
    q: "Quelle valeur dans une table de routage représente la fiabilité et est utilisée pour déterminer l'itinéraire à installer lorsque plusieurs routes existent vers la même destination ?",
    m: false,
    o: [
      "Protocole de routage",
      "Métrique",
      "Distance administrative",
      "Interface de sortie",
    ],
    a: [2],
    e: "La distance administrative (DA) indique la fiabilité d'une source de routage. Plus la DA est faible, plus la route est préférée. Elle est utilisée pour choisir entre plusieurs routes vers la même destination.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle commande configure une route statique sur R1 pour que le trafic des deux LAN puisse atteindre le réseau distant 2001:db8:1:4::/64 ?",
    m: false,
    o: [
      "ipv6 route ::/0 serial0/0/0",
      "ipv6 route 2001:db8:1:4::/64 2001:db8:1:3::2",
      "ipv6 route 2001:db8:1::/65 2001:db8:1:3::1",
      "ipv6 route 2001:db8:1:4::/64 2001:db8:1:3::1",
    ],
    a: [3],
    e: "La commande spécifie le réseau de destination (2001:db8:1:4::/64) et l'adresse du tronçon suivant (2001:db8:1:3::1) pour atteindre le réseau distant.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle commande configure une route statique sur le routeur A pour diriger le trafic du LAN A vers le LAN C ?",
    m: false,
    o: [
      "A(config)# ip route 192.168.4.0 255.255.255.0 192.168.5.2",
      "A(config)# ip route 192.168.3.2 255.255.255.0 192.168.4.0",
      "A(config)# ip route 192.168.4.0 255.255.255.0 192.168.3.2",
      "A(config)# ip route 192.168.5.0 255.255.255.0 192.168.3.2",
      "A(config)# ip route 192.168.3.0 255.255.255.0 192.168.3.1",
    ],
    a: [2],
    e: "Pour atteindre le LAN C (192.168.4.0), le routeur A envoie le trafic vers 192.168.3.2 (adresse du routeur intermédiaire sur le réseau entre A et C).",
  },
  {
    c: "routing",
    q: "Examinez la commande : ip route 192.168.10.0 255.255.255.0 10.10.10.2 5. Comment l'administrateur devrait-il tester cette configuration de route flottante ?",
    m: false,
    o: [
      "Supprimer la route de la passerelle par défaut du routeur.",
      "Envoyer un ping au réseau 192.168.10.0 à l'adresse 10.10.10.2.",
      "Arrêter manuellement l'interface du routeur utilisée comme route principale.",
      "Envoyer un ping à une adresse valide du réseau 192.168.10.0/24.",
    ],
    a: [2],
    e: "Pour tester une route flottante, il faut simuler une panne de la route principale en désactivant l'interface principale et vérifier que la route flottante prend le relais.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quel ensemble de commandes configurera des routes statiques permettant aux routeurs Park et Alta de transférer des paquets vers chaque réseau local et de diriger tout autre trafic vers Internet ?",
    m: false,
    o: [
      "Park(config)# ip route 0.0.0.0 0.0.0.0 192.168.14.1 / Alta(config)# ip route 10.0.234.0... / Alta(config)# ip route 198.18.222.0 255.255.255.255 s0/0/0",
      "Park(config)# ip route 172.16.67.0... / Alta(config)# ip route 10.0.234.0... / Alta(config)# ip route 0.0.0.0 0.0.0.0 s0/0/1",
      "Park(config)# ip route 0.0.0.0 0.0.0.0 192.168.14.1 / Alta(config)# ip route 10.0.234.0... / Alta(config)# ip route 0.0.0.0 0.0.0.0 s0/0/0",
      "Park(config)# ip route 172.16.67.0... / Park(config)# ip route 0.0.0.0 0.0.0.0 192.168.14.1 / Alta(config)# ip route 10.0.234.0...",
    ],
    a: [2],
    e: "Park utilise une route par défaut vers Edge (via Alta). Alta a une route vers le LAN de Park et une route par défaut vers Internet via s0/0/0.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 172.19.115.206 ?",
    m: false,
    o: [
      "Le paquet prend la passerelle de dernier recours",
      "GigabitEthernet0/1",
      "Aucun, le paquet est abandonné",
      "GigabitEthernet0/0",
    ],
    a: [3],
    e: "Le routeur effectue une recherche de correspondance la plus longue et détermine que 172.19.115.206 correspond à une route sortant par GigabitEthernet0/0.",
  },
  {
    c: "routing",
    q: "Associez chaque entrée de la table de routage à la fonction correspondante.",
    m: false,
    o: [
      "C=réseau directement connecté, L=adresse IP locale interface, S=route statique, O=route OSPF, *=route par défaut candidate",
      "C=route statique, L=réseau connecté, S=adresse IP locale, O=route RIP, *=route flottante",
      "C=route OSPF, L=route statique, S=réseau directement connecté, O=adresse locale, *=route distante",
      "C=route RIP, L=route EIGRP, S=route OSPF, O=réseau connecté, *=route par défaut",
    ],
    a: [0],
    e: "Dans la table de routage IOS : C=directement connecté, L=adresse locale, S=statique, O=OSPF, R=RIP, D=EIGRP, *=meilleure candidate route par défaut.",
  },
  {
    c: "routing",
    q: "Considérez la commande : ip route 192.168.10.0 255.255.255.0 10.10.10.2 5. Quelle route doit être hors service pour que cette route statique flottante apparaisse dans la table de routage ?",
    m: false,
    o: [
      "Une route par défaut",
      "Une route statique vers le réseau 192.168.10.0/24",
      "Une route apprise via OSPF vers le réseau 192.168.10.0/24",
      "Une route apprise via EIGRP vers le réseau 192.168.10.0/24",
    ],
    a: [1],
    e: "DA 5 est supérieure à la DA statique par défaut (1). Cette route n'est active que si une route statique normale (DA 1) vers 192.168.10.0/24 disparaît.",
  },
  {
    c: "routing",
    q: "Quelle caractéristique complète l'énoncé suivant : « Lorsqu'une route statique IPv6 de sauvegarde est configurée, la commande distance est utilisée avec… »",
    m: false,
    o: [
      "la commande show ipv6 route static",
      "un itinéraire hôte de destination avec un préfixe /128",
      "une distance administrative de 2",
      "l'adresse de saut suivant de deux routeurs adjacents différents",
    ],
    a: [2],
    e: "Une distance administrative spécifique est attribuée à la route de sauvegarde pour la rendre moins préférable que la route principale.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 172.25.128.244 ?",
    m: false,
    o: [
      "GigabitEthernet0/0",
      "GigabitEthernet0/1",
      "Serial0/0/1",
      "Aucun, le paquet est abandonné",
    ],
    a: [0],
    e: "La table de routage indique que 172.25.128.244 est accessible via GigabitEthernet0/0 selon la correspondance la plus longue.",
  },
  {
    c: "routing",
    q: "Quelle route est associée à la distance administrative la plus courte (la plus fiable) ?",
    m: false,
    o: [
      "Un réseau directement connecté",
      "Une route reçue via le protocole OSPF",
      "Une route statique",
      "Une route reçue via le protocole EIGRP",
    ],
    a: [0],
    e: "Les réseaux directement connectés ont une DA de 0 (la plus fiable). Statique=1, EIGRP=90, OSPF=110, RIP=120.",
  },
  {
    c: "routing",
    q: "Considérez la commande : ip route 192.168.10.0 255.255.255.0 10.10.10.2 5. Que signifie le 5 à la fin de cette commande ?",
    m: false,
    o: [
      "Nombre maximal de sauts pour atteindre le réseau 192.168.10.0/24",
      "Numéro de l'interface de sortie",
      "Métrique de la route",
      "Distance administrative de la route statique",
    ],
    a: [3],
    e: "Dans ip route [réseau] [masque] [next-hop] [DA], le dernier paramètre est la distance administrative. Ici 5 est la DA attribuée à cette route.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 10.3.86.2 ?",
    m: false,
    o: ["Serial0/0/1", "Serial0/0/0", "GigabitEthernet0/1", "GigabitEthernet0/0"],
    a: [1],
    e: "Le routeur consulte sa table de routage et détermine que 10.3.86.2 correspond à une route sortant par Serial0/0/0.",
  },
  {
    c: "routing",
    q: "Quelle caractéristique complète l'énoncé suivant : « Lorsqu'une route statique IPv6 est configurée, il est d'abord nécessaire de configurer… »",
    m: false,
    o: [
      "la commande ipv6 unicast-routing",
      "l'adresse de saut suivant de deux routeurs adjacents différents",
      "une adresse lien-local IPv6 sur le routeur adjacent",
      "une distance administrative de 2",
    ],
    a: [0],
    e: "La commande ipv6 unicast-routing doit être activée globalement sur le routeur avant de configurer des routes statiques IPv6.",
  },
  {
    c: "routing",
    q: "Quelle caractéristique complète l'énoncé suivant : « Lorsqu'une route statique IPv6 est configurée, une configuration entièrement spécifiée doit être utilisée avec… »",
    m: false,
    o: [
      "la commande ipv6 unicast-routing",
      "l'adresse de saut suivant de deux routeurs adjacents différents",
      "::/0",
      "un réseau multi-accès directement connecté",
    ],
    a: [3],
    e: "Sur un réseau multi-accès (Ethernet), une route entièrement spécifiée est nécessaire car il y a plusieurs voisins possibles sur le même réseau.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 172.25.128.244 ?",
    m: false,
    o: [
      "GigabitEthernet0/0",
      "GigabitEthernet0/1",
      "Serial0/0/1",
      "Aucun, le paquet est abandonné",
    ],
    a: [0],
    e: "Le routeur détermine l'interface de sortie en effectuant une correspondance la plus longue dans sa table de routage pour la destination 172.25.128.244.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 10.55.99.78 ?",
    m: false,
    o: ["Serial0/0/1", "GigabitEthernet0/1", "Serial0/0/0", "GigabitEthernet0/0"],
    a: [2],
    e: "Selon la table de routage affichée, 10.55.99.78 correspond à la route sortant par Serial0/0/0.",
  },
  {
    c: "routing",
    q: "Quelle caractéristique complète l'énoncé suivant : « Lorsqu'une route statique IPv6 est configurée, il est possible que la même adresse lien-local IPv6 soit utilisée pour… »",
    m: false,
    o: [
      "une distance administrative de 2",
      "la commande ipv6 unicast-routing",
      "l'adresse de saut suivant de deux routeurs adjacents différents",
      "un itinéraire hôte de destination avec un préfixe /128",
    ],
    a: [2],
    e: "La même adresse lien-local peut apparaître sur plusieurs interfaces de différents routeurs. C'est pourquoi une route entièrement spécifiée est nécessaire pour éviter l'ambiguïté.",
  },
  {
    c: "routing",
    q: "Reportez-vous à l'illustration. Quelle interface sera l'interface de sortie pour transmettre un paquet dont l'adresse IP de destination est 192.168.71.52 ?",
    m: false,
    o: [
      "Le paquet prend la passerelle de dernier recours",
      "GigabitEthernet0/1",
      "Serial0/0/0",
      "Aucun, le paquet est abandonné",
    ],
    a: [3],
    e: "Si aucune route ne correspond à 192.168.71.52 et qu'il n'y a pas de route par défaut, le routeur abandonne le paquet et envoie un message ICMP Destination Unreachable.",
  },
];
