const QUESTIONS_7_9 = [
        {
          c: "dhcp",
          q: "Associez chaque type de message DHCP à sa description. (voir illustration)",
          m: false,
          i: "2022-06-27_211435.jpg",
          o: [
            "DISCOVER=client cherche serveur / OFFER=serveur répond / REQUEST=client accepte / ACK=serveur confirme",
            "DISCOVER=serveur confirme / OFFER=client accepte / REQUEST=client cherche / ACK=serveur répond",
            "DISCOVER=client accepte / OFFER=serveur confirme / REQUEST=serveur répond / ACK=client cherche",
            "DISCOVER=serveur répond / OFFER=client cherche / REQUEST=serveur confirme / ACK=client accepte",
          ],
          a: [0],
          e: "DHCPDISCOVER = client cherche serveur. DHCPOFFER = serveur propose. DHCPREQUEST = client accepte. DHCPACK = serveur confirme le bail.",
        },
        {
          c: "dhcp",
          q: "Quel protocole automatise l'attribution des adresses IP, et quel numéro de port utilise-t-il ?",
          m: true,
          o: ["DHCP", "DNS", "Protocole SMB", "Port 53", "Port 67", "Port 80"],
          a: [0, 4],
          e: "DHCP automatise l'attribution des adresses IP et utilise le port UDP 67 (serveur). Port 53 = DNS, port 80 = HTTP.",
        },
        {
          c: "dhcp",
          q: "Lorsque le bail de 5 jours a expiré, quelles adresses L2 et L3 le message DHCP contient-il ?",
          m: false,
          o: [
            "L'adresse MAC du serveur DHCP et 255.255.255.255",
            "FF-FF-FF-FF-FF-FF et l'adresse IPv4 du serveur DHCP",
            "Les adresses MAC et IPv4 du serveur DHCP",
            "FF-FF-FF-FF-FF-FF et 255.255.255.255",
          ],
          a: [3],
          e: "Le DHCPDISCOVER est en diffusion : adresse MAC de destination = FF-FF-FF-FF-FF-FF, adresse IP de destination = 255.255.255.255.",
        },
        {
          c: "dhcp",
          q: "Quelle commande permet de vérifier l'adresse IP attribuée à une adresse MAC donnée ?",
          m: false,
          o: [
            "Router# show ip dhcp binding",
            "Router# show running-config | section dhcp",
            "Router# show ip dhcp server statistics",
            "Router# show ip dhcp pool",
          ],
          a: [0],
          e: "'show ip dhcp binding' affiche les baux : adresses IP, adresses MAC, expiration et type de bail.",
        },
        {
          c: "dhcp",
          q: "Quel jeu de commandes configure un routeur comme serveur DHCP pour 192.168.100.0/23 en réservant les 10 premières et la dernière adresse ?",
          m: false,
          o: [
            "ip dhcp excluded-address 192.168.100.1 192.168.100.10 | excluded-address 192.168.100.254 | ip dhcp pool LAN-POOL-100 | network 192.168.100.0 255.255.255.0 | ip default-gateway 192.168.100.1",
            "ip dhcp excluded-address 192.168.100.1 192.168.100.9 | excluded-address 192.168.101.254 | ip dhcp pool LAN-POOL-100 | ip network 192.168.100.0 255.255.254.0 | ip default-gateway 192.168.100.1",
            "ip dhcp excluded-address 192.168.100.1 192.168.100.10 | excluded-address 192.168.101.254 | ip dhcp pool LAN-POOL-100 | network 192.168.100.0 255.255.254.0 | default-router 192.168.100.1",
            "dhcp pool LAN-POOL-100 | excluded-address 192.168.100.1 192.168.100.9 | excluded-address 192.168.100.254 | network 192.168.100.0 255.255.254.0 | default-router 192.168.101.1",
          ],
          a: [2],
          e: "/23 = masque 255.255.254.0. La plage est 192.168.100.1 à 192.168.101.254. Les commandes 'dhcp pool', 'ip default-gateway' et 'ip network' sont incorrectes.",
        },
        {
          c: "dhcp",
          q: "Quel message est envoyé par le serveur pour informer le client qu'il peut utiliser les informations IP fournies ?",
          m: false,
          o: [
            "DHCPOFFER",
            "DHCPREQUEST",
            "DHCPDISCOVER",
            "DHCPACK",
            "DHCPNACK",
          ],
          a: [3],
          e: "DHCPACK = le serveur confirme et finalise le bail avec le client.",
        },
        {
          c: "dhcp",
          q: "Que se passe-t-il lorsque les serveurs DHCP ne sont pas opérationnels ?",
          m: false,
          o: [
            "Les postes reçoivent des adresses dans la plage 169.254.0.0/16.",
            "Les postes reçoivent l'adresse IP 127.0.0.1.",
            "Les postes reçoivent l'adresse IP 0.0.0.0.",
            "Les postes reçoivent des adresses dans la plage 10.0.0.0/8.",
          ],
          a: [0],
          e: "Quand aucun serveur DHCP ne répond, Windows attribue automatiquement une adresse APIPA en 169.254.0.0/16.",
        },
        {
          c: "dhcp",
          q: "Quelle information indique qu'un ordinateur Windows n'a pas reçu d'adresse IPv4 d'un serveur DHCP ?",
          m: false,
          o: [
            "L'ordinateur reçoit une adresse IP commençant par 169.254.",
            "L'ordinateur ne peut pas pinguer 127.0.0.1.",
            "L'ordinateur ne peut pas pinguer les autres appareils en 169.254.0.0/16.",
            "Windows affiche un message d'expiration DHCP.",
          ],
          a: [0],
          e: "Windows s'auto-attribue une adresse APIPA en 169.254.x.x quand aucun serveur DHCP ne répond.",
        },
        {
          c: "dhcp",
          q: "Dans un café avec routeur sans fil et modem DSL, quelle méthode configure la connexion vers le FAI ?",
          m: false,
          o: [
            "Définir le modem DSL comme client DHCP pour le FAI et serveur DHCP pour l'interne.",
            "Définir le modem DSL comme client DHCP pour obtenir une IP publique du routeur.",
            "Définir la connexion entre le routeur et le modem comme réseau IP privé.",
            "Définir la connexion WAN dans le routeur sans fil comme client DHCP.",
          ],
          a: [3],
          e: "La connexion WAN du routeur sans fil est configurée en tant que client DHCP pour obtenir une adresse IP du FAI.",
        },
        {
          c: "dhcp",
          q: "Quelle est la raison pour laquelle un ISP attribue couramment une adresse DHCP à un routeur sans fil en environnement SOHO ?",
          m: false,
          o: [
            "meilleure connectivité",
            "configuration facile sur pare-feu FAI",
            "gestion facile des adresses IP",
            "meilleure performance du réseau",
          ],
          a: [2],
          e: "DHCP facilite la gestion de l'adressage IP : les adresses sont dynamiquement réaffectées lorsqu'un client est supprimé.",
        },
        {
          c: "dhcp",
          q: "Quels sont les deux ports UDP utilisés pour transférer le trafic DHCP ?",
          m: true,
          o: ["67", "23", "80", "68", "53"],
          a: [0, 3],
          e: "DHCP utilise UDP 67 (serveur) et UDP 68 (client).",
        },
        {
          c: "dhcp",
          q: "Quelle information est vérifiée par la commande 'show ip dhcp binding' ?",
          m: false,
          o: [
            "Les adresses IPv4 exclues du pool DHCPv4",
            "Les adresses IPv4 attribuées aux hôtes par le serveur DHCP",
            "Le nombre d'adresses IP disponibles dans le pool DHCP",
            "La confirmation de réception des messages DHCPDISCOVER",
          ],
          a: [1],
          e: "'show ip dhcp binding' affiche la liste des adresses IPv4 et MAC attribuées aux hôtes.",
        },
        {
          c: "dhcp",
          q: "Comment un périphérique client peut-il obtenir une adresse IP d'un serveur DHCP configuré à 192.168.1.1 ?",
          m: false,
          o: [
            "En envoyant un DHCPDISCOVER à l'adresse physique FF-FF-FF-FF-FF-FF.",
            "En envoyant un DHCPREQUEST à l'adresse IP 255.255.255.255.",
            "En sélectionnant statiquement une adresse parmi celles du serveur DHCP.",
            "En envoyant un DHCPREQUEST à l'adresse de la passerelle par défaut.",
          ],
          a: [0],
          e: "Le client envoie un DHCPDISCOVER en diffusion à FF-FF-FF-FF-FF-FF car il ne connaît pas l'adresse du serveur DHCP.",
        },
        {
          c: "dhcp",
          q: "Quel avantage présente la configuration d'un routeur Cisco comme agent de relais DHCP ?",
          m: false,
          o: [
            "Cela permet de fournir des services de relais pour plusieurs services UDP.",
            "Cela permet la transmission des messages de diffusion et de multidiffusion.",
            "Cela permettra la diffusion des messages DHCPDISCOVER sans modification.",
            "Cela réduit le délai de réponse d'un serveur DHCP.",
          ],
          a: [0],
          e: "La commande 'ip helper-address' transmet 8 services UDP par défaut : DHCP, DNS, TFTP, TACACS, heure, NetBIOS.",
        },
        {
          c: "dhcp",
          q: "Associez les objectifs avec les types de message DHCP correspondants. (voir illustration)",
          m: false,
          i: "2022-06-27_213014.jpg",
          o: [
            "DISCOVER=identifier serveurs / OFFER=proposer bail / REQUEST=identifier serveur choisi / ACK=finaliser bail / NAK=bail non valide",
            "DISCOVER=finaliser bail / OFFER=identifier serveurs / REQUEST=proposer bail / ACK=serveur choisi / NAK=bail valide",
            "DISCOVER=proposer bail / OFFER=finaliser bail / REQUEST=identifier serveurs / ACK=bail non valide",
            "DISCOVER=identifier serveur choisi / OFFER=bail non valide / REQUEST=finaliser bail / ACK=proposer bail",
          ],
          a: [0],
          e: "DISCOVER=trouver serveurs / OFFER=proposer bail / REQUEST=indiquer serveur choisi / ACK=finaliser bail / NAK=bail non valide.",
        },
        {
          c: "dhcp",
          q: "Que configurer sur le routeur pour que les stations SLAAC obtiennent le préfixe IPv6 ?",
          m: false,
          o: [
            "R1(config)# ipv6 unicast-routing",
            "R1(config)# ipv6 dhcp pool <nom>",
            "R1(config-if)# ipv6 nd other-config-flag",
            "R1(config-if)# ipv6 enable",
          ],
          a: [0],
          e: "La commande 'ipv6 unicast-routing' active le routage IPv6 et permet l'envoi de messages RA contenant le préfixe.",
        },
        {
          c: "dhcp",
          q: "PC-A ne reçoit pas d'adresse IPv6 depuis le serveur DHCPv6. Quel est le problème ? (voir illustration)",
          m: false,
          i: "2022-06-27_220352.jpg",
          o: [
            "La commande ipv6 nd managed-config-flag doit être ipv6 nd other-config-flag.",
            "La commande ipv6 dhcp relay doit utiliser l'adresse link-local du serveur DHCP.",
            "La commande ipv6 nd managed-config-flag doit être appliquée à l'interface Gig0/1.",
            "La commande ipv6 dhcp relay doit être appliquée à l'interface Gig0/0.",
          ],
          a: [3],
          e: "La commande 'ipv6 dhcp relay' doit être appliquée à l'interface côté clients (Gig0/0), pas côté serveur.",
        },
        {
          c: "dhcp",
          q: "Les clients ne récupèrent pas les adresses DNS du serveur DHCPv6 sans état. Quelle est la cause probable ? (voir illustration)",
          m: false,
          i: "2022-06-27_220303.jpg",
          o: [
            "Les clients ne peuvent pas communiquer avec le serveur DHCPv6 (0 clients actifs).",
            "Le routeur est configuré pour un fonctionnement SLAAC.",
            "L'adresse DNS n'est pas sur le même réseau que les clients.",
            "L'interface Gigabit Ethernet n'est pas activée.",
          ],
          a: [1],
          e: "Le routeur est en mode SLAAC (indicateurs M et O à 0 par défaut). Pour DHCPv6 sans état, il faut ajouter 'ipv6 nd other-config-flag'.",
        },
        {
          c: "dhcp",
          q: "Faites correspondre les types de message DHCPv6 à l'ordre du processus DHCPv6 avec état. (voir illustration)",
          m: false,
          i: "2022-06-27_213426.jpg",
          o: [
            "SOLICIT → ADVERTISE → REQUEST → REPLY",
            "DISCOVER → OFFER → REQUEST → ACK",
            "SOLICIT → OFFER → REQUEST → ACK",
            "ADVERTISE → SOLICIT → REPLY → REQUEST",
          ],
          a: [0],
          e: "DHCPv6 avec état : SOLICIT (client cherche) → ADVERTISE (serveur annonce) → REQUEST (client demande) → REPLY (serveur confirme).",
        },
        {
          c: "dhcp",
          q: "Quelles conclusions tirez-vous des commandes de configuration DHCPv6 sur le routeur ? (voir illustration)",
          m: false,
          i: "2022-06-27_220213.jpg",
          o: [
            "Le routeur est configuré pour un fonctionnement DHCPv6 sans état.",
            "Les clients doivent configurer les ID d'interface supérieurs à 0010.",
            "Le routeur est configuré pour DHCPv6 avec état, mais la configuration du pool est incomplète.",
            "Le nom du serveur DHCPv6 est ACAD_CLASS.",
          ],
          a: [0],
          e: "L'indicateur O=1 (other-config-flag) et M=0 = DHCPv6 sans état. ACAD_CLASS est le nom du pool DHCP, pas du serveur.",
        },
        {
          c: "dhcp",
          q: "Associez chaque description au type de serveur DHCPv6 correspondant. (voir illustration)",
          m: false,
          i: "2022-06-27_213733.jpg",
          o: [
            "Sans état = adresses via SLAAC + infos via DHCPv6 / Avec état = tout via DHCPv6",
            "Sans état = tout via DHCPv6 / Avec état = adresses via SLAAC + infos via DHCPv6",
            "Sans état = tout via SLAAC / Avec état = tout via DHCPv6",
            "Sans état = tout via DHCPv6 / Avec état = tout via SLAAC",
          ],
          a: [0],
          e: "DHCPv6 sans état : adresses via SLAAC + infos supplémentaires (DNS) via DHCPv6. Avec état : toutes les informations viennent du serveur DHCPv6.",
        },
        {
          c: "dhcp",
          q: "Quelle proposition désigne une fonction associée au protocole HSRP ?",
          m: false,
          o: [
            "Le protocole HSRP utilise des routeurs actifs et de secours.",
            "Cela permet d'équilibrer la charge entre un groupe de routeurs redondants.",
            "HSRP n'est pas un protocole propriétaire.",
            "Il utilise des messages ICMP pour attribuer la passerelle par défaut aux hôtes.",
          ],
          a: [0],
          e: "HSRP est propriétaire Cisco et utilise un routeur actif et un routeur de secours. GLBP = équilibrage de charge. VRRP = non propriétaire.",
        },
        {
          c: "dhcp",
          q: "Quel protocole peut être configuré sur R1 et R2 pour permettre l'équilibrage de la charge du trafic LAN entre les deux passerelles ? (voir illustration)",
          m: false,
          i: "2022-06-27_220131.jpg",
          o: ["PVST", "PVST+", "STP", "GLBP"],
          a: [3],
          e: "GLBP (Gateway Load Balancing Protocol) permet à plusieurs routeurs d'agir comme passerelle par défaut tout en équilibrant la charge.",
        },
        {
          c: "dhcp",
          q: "Quelle adresse de passerelle IPv4 doit être configurée sur l'hôte utilisant un protocole FHRP ? (voir illustration)",
          m: false,
          i: "2022-06-27_220038.jpg",
          o: ["192.168.2.0", "192.168.2.1", "192.168.2.2", "192.168.2.100"],
          a: [3],
          e: "L'adresse de passerelle doit être l'adresse IP virtuelle du FHRP (ici GLBP) : 192.168.2.100.",
        },
        {
          c: "dhcp",
          q: "Quelle adresse MAC de destination est utilisée quand des trames sont envoyées vers la passerelle par défaut (FHRP) ? (voir illustration)",
          m: false,
          i: "2022-06-27_220003.jpg",
          o: [
            "L'adresse MAC du routeur de transfert",
            "L'adresse MAC du routeur virtuel",
            "Les adresses MAC du routeur de transfert et du routeur en veille.",
            "L'adresse MAC du routeur en veille",
          ],
          a: [1],
          e: "L'ARP retourne l'adresse MAC du routeur virtuel. Toutes les stations de travail utilisent cette adresse MAC virtuelle.",
        },
        {
          c: "dhcp",
          q: "Faites correspondre le numéro d'étape à la séquence du processus de basculement HSRP. (voir illustration)",
          m: false,
          i: "2022-06-27_214135.jpg",
          o: [
            "Défaillance active → absence de hello → fin du timer → routeur de secours prend en charge",
            "Défaillance active → routeur de secours prend en charge → absence de hello → fin du timer",
            "Absence de hello → fin du timer → routeur de secours prend en charge → défaillance active",
            "Fin du timer → défaillance active → absence de hello → routeur de secours prend en charge",
          ],
          a: [0],
          e: "Processus HSRP : 1.Routeur actif tombe. 2.Plus de messages hello. 3.Timer expire. 4.Routeur de secours prend le rôle actif.",
        },
        {
          c: "dhcp",
          q: "Faire correspondre les protocoles FHRP à leur description. (voir illustration)",
          m: false,
          i: "2022-06-27_214339.jpg",
          o: [
            "GLBP=partage de charge Cisco / HSRP=actif/secours Cisco / VRRP=standard ouvert maître/secours",
            "GLBP=standard ouvert / HSRP=partage de charge Cisco / VRRP=actif/secours Cisco",
            "GLBP=maître/secours Cisco / HSRP=standard ouvert / VRRP=partage de charge Cisco",
            "GLBP=actif/secours Cisco / HSRP=standard ouvert / VRRP=partage de charge",
          ],
          a: [0],
          e: "GLBP = Cisco + partage de charge. HSRP = Cisco + actif/secours. VRRP = standard ouvert + maître virtuel/secours.",
        },
        {
          c: "dhcp",
          q: "Quelle implémentation FHRP est un protocole électoral non propriétaire uniquement IPv4 avec évolutivité limitée ?",
          m: false,
          o: ["IRDP", "GLBP pour IPv6", "GLBP", "VRRPv2"],
          a: [3],
          e: "VRRPv2 est un protocole non propriétaire (standard IEEE) uniquement IPv4 avec évolutivité limitée.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 10.92.71.0/25. L'admin réserve 8 adresses pour les serveurs. Combien d'adresses restent pour les autres hôtes ?",
          m: false,
          o: ["118", "116", "119", "122", "108"],
          a: [0],
          e: "/25 = 126 hôtes max. 126 - 8 = 118 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "Associez les types de message DHCP à l'ordre du processus DHCPv4. (voir illustration)",
          m: false,
          i: "2022-06-27_214544.jpg",
          o: [
            "DISCOVER → OFFER → REQUEST → ACK",
            "OFFER → DISCOVER → ACK → REQUEST",
            "REQUEST → DISCOVER → OFFER → ACK",
            "DISCOVER → REQUEST → OFFER → ACK",
          ],
          a: [0],
          e: "DHCPv4 : DISCOVER (client diffuse) → OFFER (serveur propose) → REQUEST (client accepte) → ACK (serveur confirme).",
        },
        {
          c: "dhcp",
          q: "Comment un hôte vérifie-t-il que son adresse IPv6 obtenue via SLAAC/DHCPv6 est unique ?",
          m: false,
          o: [
            "Il envoie une diffusion ARP ; si aucun hôte ne répond, l'adresse est unique.",
            "Il envoie une sollicitation de voisin ICMPv6 ; si aucune annonce de voisin n'est renvoyée, l'adresse est unique.",
            "Il vérifie le cache du voisin local ; si l'adresse n'est pas mise en cache, elle est unique.",
            "Il envoie un echo ICMPv6 ; si aucune réponse n'est renvoyée, l'adresse est unique.",
          ],
          a: [1],
          e: "La détection d'adresse dupliquée (DAD) utilise une sollicitation de voisin ICMPv6. Si aucune annonce de voisin n'est reçue, l'adresse est unique.",
        },
        {
          c: "dhcp",
          q: "Quelle déclaration décrit HSRP ?",
          m: false,
          o: [
            "Utilisé dans un groupe de routeurs pour sélectionner un périphérique actif et un périphérique de secours pour les services de passerelle.",
            "Choix d'un routeur comme routeur virtuel principal, les autres servant de routeurs de secours.",
            "Il utilise ICMP pour permettre aux hôtes IPv4 de localiser les routeurs.",
            "C'est un protocole standard ouvert.",
          ],
          a: [0],
          e: "HSRP est propriétaire Cisco, utilise un périphérique actif et un de secours. VRRP élit un maître virtuel. IRDP utilise ICMP.",
        },
        {
          c: "dhcp",
          q: "Dans Packet Tracer, quel mot-clé est affiché sur www.netacad.com ? (voir illustration)",
          m: false,
          i: "2022-06-27_222126.jpg",
          o: ["réseau", "Routeur", "commutateur", "DHCP", "Cisco", "IPv6"],
          a: [3],
          e: "Il manque 'ipv6 nd other-config-flag' sur Gig0/0 pour que l'hôte reçoive l'adresse DNS via DHCPv6 sans état. Le mot affiché est DHCP.",
        },
        {
          c: "dhcp",
          q: "Quel message un hôte IPv4 utilise-t-il pour répondre à un DHCPOFFER ?",
          m: false,
          o: ["DHCPDISCOVER", "DHCPACK", "DHCPOFFER", "DHCPREQUEST"],
          a: [3],
          e: "Quand le client reçoit un DHCPOFFER, il répond par un DHCPREQUEST diffusé pour indiquer qu'il accepte l'offre.",
        },
        {
          c: "dhcp",
          q: "Quelle commande d'interface permet d'obtenir automatiquement une adresse IPv4 d'un FAI via DHCP ?",
          m: false,
          o: [
            "ip address dhcp",
            "ip dhcp pool",
            "ip helper-address",
            "service dhcp",
          ],
          a: [0],
          e: "La commande 'ip address dhcp' configure une interface en tant que client DHCP.",
        },
        {
          c: "dhcp",
          q: "Quel type de message un client DHCP envoie-t-il lorsque le bail de son adresse IP a expiré ?",
          m: false,
          o: [
            "Un message monodiffusion DHCPDISCOVER",
            "Un message monodiffusion DHCPREQUEST",
            "Un message de diffusion DHCPDISCOVER",
            "Un message de diffusion DHCPREQUEST",
          ],
          a: [1],
          e: "Lorsque le bail expire, le client envoie un DHCPREQUEST en monodiffusion directement au serveur qui a fourni l'adresse.",
        },
        {
          c: "dhcp",
          q: "Quel message DHCPv4 un client envoie-t-il pour accepter une adresse IPv4 offerte par un serveur DHCP ?",
          m: false,
          o: [
            "Diffusion DHCPREQUEST",
            "Diffusion DHCPACK",
            "Monodiffusion DHCPREQUEST",
            "Monodiffusion DHCPACK",
          ],
          a: [0],
          e: "Le client envoie un DHCPREQUEST en diffusion pour indiquer au serveur qu'il accepte l'offre ET informer les autres serveurs que leurs offres sont rejetées.",
        },
        {
          c: "dhcp",
          q: "La commande 'ip dhcp excluded-address 10.0.15.1 10.0.15.15' est saisie sur un routeur. Quel est le résultat ?",
          m: false,
          o: [
            "Le routeur ne permet de louer que les adresses spécifiées.",
            "Le routeur exclut 15 adresses IP de la location aux clients DHCP.",
            "Le routeur exclut uniquement les adresses 10.0.15.1 et 10.0.15.15.",
            "Le routeur crée automatiquement un pool DHCP via un masque /28.",
          ],
          a: [1],
          e: "La commande exclut une plage de 15 adresses (de .1 à .15 inclus) de la location aux clients DHCP.",
        },
        {
          c: "dhcp",
          q: "Parmi les propositions relatives au fonctionnement DHCP, laquelle est exacte ?",
          m: false,
          o: [
            "Si le client reçoit plusieurs DHCPOFFER, il envoie un DHCPREQUEST monodiffusion au serveur choisi.",
            "Le message DHCPDISCOVER contient l'adresse IP et le masque à attribuer.",
            "Un client doit attendre l'expiration du bail avant d'envoyer un autre DHCPREQUEST.",
            "Quand un périphérique configuré pour DHCP démarre, le client diffuse un DHCPDISCOVER pour identifier tout serveur DHCP disponible.",
          ],
          a: [3],
          e: "Le client diffuse un DHCPDISCOVER pour identifier les serveurs disponibles sur le réseau.",
        },
        {
          c: "dhcp",
          q: "Avec SLAAC, quelle adresse le client utilise-t-il comme passerelle par défaut ?",
          m: false,
          o: [
            "L'adresse locale unique de l'interface du routeur connectée au réseau",
            "L'adresse de monodiffusion globale de l'interface du routeur connectée au réseau",
            "L'adresse link-local de l'interface du routeur connectée au réseau",
            "L'adresse de multidiffusion destinée à tous les routeurs",
          ],
          a: [2],
          e: "Avec SLAAC, le client utilise l'adresse link-local de l'interface du routeur (reçue dans le message RA) comme passerelle par défaut IPv6.",
        },
        {
          c: "dhcp",
          q: "Quelle implémentation FHRP est un protocole d'élection IPv4 exclusif qui a un routeur principal par groupe ?",
          m: false,
          o: ["VRRPv3", "HSRP pour IPv6", "VRRPv2", "HSRP"],
          a: [3],
          e: "HSRP est le protocole propriétaire Cisco d'élection pour IPv4 avec un routeur actif (principal) et un de secours par groupe.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 10.19.44.0/24. L'admin réserve 3 adresses pour les serveurs. Combien d'adresses restent ?",
          m: false,
          o: ["251", "241", "249", "255", "252"],
          a: [0],
          e: "/24 = 254 hôtes. 254 - 3 = 251 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "Indicateur M=0 et O=1 dans les messages RA : quel est l'effet sur la configuration IPv6 d'un PC ?",
          m: false,
          o: [
            "Il doit contacter un serveur DHCPv6 pour toutes les informations.",
            "Il doit contacter un serveur DHCPv6 pour le préfixe, la longueur de préfixe et un ID d'interface.",
            "Il doit utiliser exclusivement les informations du message RA.",
            "Il doit utiliser les informations du message RA et contacter un serveur DHCPv6 pour les informations supplémentaires.",
          ],
          a: [3],
          e: "M=0 / O=1 = DHCPv6 sans état : le client utilise SLAAC pour l'adresse et DHCPv6 pour les infos supplémentaires (DNS, domaine...).",
        },
        {
          c: "dhcp",
          q: "D'après le résultat affiché, quel type d'adressage IPv6 est configuré ? (voir illustration)",
          m: false,
          i: "2022-07-01_161226.jpg",
          o: [
            "Link-local statique",
            "SLAAC",
            "stateless DHCPv6",
            "stateful DHCPv6",
          ],
          a: [2],
          e: "Le pool DHCPv6 sans état contient uniquement des infos comme DNS et nom de domaine (pas de plage d'adresses). L'indicateur O=1 confirme le mode sans état.",
        },
        {
          c: "dhcp",
          q: "Que faut-il faire pour permettre à PC-A de recevoir une adresse IPv6 depuis le serveur DHCPv6 ? (voir illustration)",
          m: false,
          i: "2022-07-01_161318.jpg",
          o: [
            "Ajouter l'adresse IPv6 2001:DB8:1234:5678::10/64 à l'interface du serveur DHCPv6.",
            "Ajouter la commande ipv6 dhcp relay à l'interface Fa0/0.",
            "Configurer la commande ipv6 nd managed-config-flag sur l'interface Fa0/1.",
            "Remplacer ipv6 nd managed-config-flag par ipv6 nd other-config-flag.",
          ],
          a: [1],
          e: "Les messages DHCPv6 client ont une portée link-local. La commande 'ipv6 dhcp relay' doit être ajoutée sur l'interface côté client (Fa0/0).",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 10.19.44.0/24. L'admin réserve 6 adresses pour les serveurs. Combien d'adresses restent ?",
          m: false,
          o: ["252", "248", "238", "249", "246"],
          a: [1],
          e: "/24 = 254 hôtes. 254 - 6 = 248 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "PC1 est arrêté depuis 2 semaines (bail expiré). Quelle adresse IP de destination est dans l'en-tête IP ? (voir illustration)",
          m: false,
          i: "2022-07-01_161424.jpg",
          o: ["192.168.1.255", "192.168.1.1", "255.255.255.255", "192.168.1.8"],
          a: [2],
          e: "Le DHCPDISCOVER est en diffusion : adresse de destination IP = 255.255.255.255 et MAC = FF:FF:FF:FF:FF:FF.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 192.168.234.0/27. L'admin réserve 22 adresses pour les téléphones IP. Combien d'adresses restent ?",
          m: false,
          o: ["0", "21", "10", "8", "18"],
          a: [3],
          e: "/27 = 30 hôtes. 30 - 22 = 8 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "Le nombre de clients actifs est 0 dans show ipv6 dhcp pool. Quelle est l'explication ? (voir illustration)",
          m: false,
          i: "2022-07-02_101403.jpg",
          o: [
            "L'état n'est pas maintenu par le serveur DHCPv6 sous l'opération DHCPv6 sans état.",
            "L'adresse de passerelle par défaut n'est pas fournie dans le pool.",
            "La configuration du pool n'a aucune plage d'adresses IPv6 spécifiée.",
            "Aucun client n'a encore communiqué avec le serveur DHCPv6.",
          ],
          a: [0],
          e: "En DHCPv6 sans état, le serveur ne maintient pas les informations d'état — les adresses sont gérées par SLAAC, pas par le serveur DHCP.",
        },
        {
          c: "dhcp",
          q: "Quelle implémentation FHRP est un protocole propriétaire Cisco qui prend en charge le partage de charge IPv4 ?",
          m: false,
          o: ["IRDP", "GLBP pour IPv6", "GLBP", "VRRPv3"],
          a: [2],
          e: "GLBP (Gateway Load Balancing Protocol) est propriétaire Cisco et supporte le partage de charge pour IPv4.",
        },
        {
          c: "dhcp",
          q: "Quelle implémentation FHRP est un protocole propriétaire Cisco qui prend en charge l'équilibrage de charge IPv6 ?",
          m: false,
          o: ["VRRPv3", "GLBP pour IPv6", "IRDP", "GLBP"],
          a: [1],
          e: "GLBP pour IPv6 est l'équivalent Cisco de GLBP pour l'adressage IPv6.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 10.7.30.0/24. L'admin réserve 5 adresses pour les imprimantes. Combien d'adresses restent ?",
          m: false,
          o: ["247", "249", "239", "253", "250"],
          a: [1],
          e: "/24 = 254 hôtes. 254 - 5 = 249 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "Quelle implémentation FHRP est un protocole non propriétaire qui s'appuie sur ICMP pour fournir la redondance IPv4 ?",
          m: false,
          o: ["IRDP", "VRRPv3", "GLBP", "GLBP pour IPv6"],
          a: [0],
          e: "IRDP (ICMP Router Discovery Protocol) est un protocole non propriétaire basé sur ICMP pour la redondance IPv4.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 172.21.121.0/25. L'admin réserve 12 adresses pour les serveurs Web. Combien d'adresses restent ?",
          m: false,
          o: ["118", "104", "114", "115", "112"],
          a: [2],
          e: "/25 = 126 hôtes. 126 - 12 = 114 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "Quelle implémentation FHRP est un protocole non propriétaire s'appuyant sur ICMP pour fournir une redondance IPv4 ?",
          m: false,
          o: ["HSRP pour IPv6", "VRRPv3", "IRDP", "VRRPv2"],
          a: [2],
          e: "IRDP est défini dans RFC 1256 et utilise ICMP pour la redondance IPv4.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 172.18.93.0/25. L'admin réserve 10 adresses pour les serveurs Web. Combien d'adresses restent ?",
          m: false,
          o: ["120", "106", "117", "114", "116"],
          a: [3],
          e: "/25 = 126 hôtes. 126 - 10 = 116 adresses disponibles.",
        },
        {
          c: "dhcp",
          q: "Pool DHCP = 192.168.184.0/26. L'admin réserve 18 adresses pour les points d'accès. Combien d'adresses restent ?",
          m: false,
          o: ["36", "46", "54", "57", "44"],
          a: [3],
          e: "/26 = 62 hôtes. 62 - 18 = 44 adresses disponibles.",
        },
];
