const QUESTIONS_10_13 = [
  {
    c: "wlan",
    q: "Quelle méthode d'authentification stocke les noms d'utilisateur et les mots de passe dans le routeur et est idéale pour les petits réseaux ?",
    m: false,
    o: [
      "AAA local",
      "AAA local sur TACACS+",
      "AAA basé sur un serveur",
      "AAA basé sur un serveur via RADIUS",
    ],
    a: [0],
    e: "L'AAA local stocke les informations d'authentification directement sur le routeur, ce qui est simple mais adapté uniquement aux petits réseaux.",
  },
  {
    c: "wlan",
    q: "Quel est le résultat d'une attaque par épuisement de ressources DHCP ?",
    m: false,
    o: [
      "Les clients légitimes ne peuvent pas louer d'adresses IP",
      "Le pirate transmet aux clients des informations incorrectes sur le DNS et la passerelle par défaut",
      "Les clients reçoivent des attributions d'adresses IP d'un serveur DHCP non autorisé",
      "Les adresses IP attribuées aux clients légitimes sont détournées",
    ],
    a: [0],
    e: "Une attaque d'épuisement DHCP envoie de nombreuses requêtes DHCP falsifiées pour épuiser le pool d'adresses, empêchant les clients légitimes d'obtenir une adresse IP.",
  },
  {
    c: "wlan",
    q: "Quelle instruction décrit le comportement d'un commutateur lorsque la table d'adresses MAC est pleine ?",
    m: false,
    o: [
      "Il traite les trames comme une monodiffusion inconnue et inonde tous les ports entrants",
      "Il traite les trames comme une monodiffusion inconnue et inonde tous les ports du domaine de collision",
      "Il traite les trames comme une monodiffusion inconnue et les inonde sur plusieurs commutateurs",
      "Il traite les trames comme une monodiffusion inconnue et inonde tous les ports du VLAN local",
    ],
    a: [3],
    e: "Lorsque la table MAC est pleine (attaque MAC flooding), le commutateur inonde toutes les trames entrantes sur tous les ports du VLAN, agissant comme un concentrateur.",
  },
  {
    c: "wlan",
    q: "Quelle composante du modèle AAA permet à un administrateur d'effectuer le suivi des personnes qui accèdent aux ressources réseau et des modifications effectuées ?",
    m: false,
    o: [
      "Accessibilité",
      "Authentification",
      "Traçabilité",
      "Autorisation",
    ],
    a: [2],
    e: "La traçabilité (Accounting) enregistre ce que l'utilisateur fait sur le réseau : connexions, commandes exécutées, ressources accédées.",
  },
  {
    c: "wlan",
    q: "Quel appareil est considéré comme le demandeur (supplicant) lors de la procédure d'authentification 802.1X ?",
    m: false,
    o: [
      "Le serveur d'authentification qui effectue l'authentification des clients",
      "Le commutateur qui contrôle l'accès physique au réseau",
      "Le routeur servant de passerelle par défaut",
      "Le client qui demande l'authentification",
    ],
    a: [3],
    e: "Dans 802.1X : le demandeur (supplicant) est le client, l'authentificateur est le commutateur/AP, et le serveur est généralement un serveur RADIUS.",
  },
  {
    c: "wlan",
    q: "L'interface Fa 0/2 du commutateur S1 a été configurée avec la commande switchport port-security mac-address 0023.189d.6456. Quelle pourrait être la raison de l'arrêt de l'interface ?",
    m: false,
    o: [
      "L'adresse MAC du PC1 qui se connecte n'est pas l'adresse MAC configurée",
      "PC1 est connecté via un câble croisé",
      "La commande switchport port-security aging a été configurée sur l'interface",
      "L'interface Fa 0/24 est configurée avec la même adresse MAC",
    ],
    a: [0],
    e: "La sécurité des ports en mode statique n'autorise qu'une adresse MAC spécifique. Si une autre adresse MAC est détectée, une violation se produit et l'interface est arrêtée (mode shutdown par défaut).",
  },
  {
    c: "wlan",
    q: "Un port est connecté à un téléphone IP avec un PC derrière. Quelle configuration de sécurité des ports est la plus appropriée pour détecter automatiquement les adresses MAC, autoriser deux appareils et arrêter le port en cas de violation ?",
    m: false,
    o: [
      "switchport port-security / maximum 2 / mac-address sticky / violation restrict",
      "switchport port-security / mac-address sticky uniquement",
      "switchport port-security / maximum 2 / mac-address sticky",
      "switchport port-security uniquement",
    ],
    a: [2],
    e: "La configuration optimale utilise : maximum 2 (téléphone + PC), mac-address sticky (apprentissage automatique), violation shutdown (par défaut).",
  },
  {
    c: "wlan",
    q: "Combien de ports parmi les commutateurs doivent être affectés comme ports fiables (trusted) dans le cadre de la surveillance DHCP (DHCP Snooping) ?",
    m: false,
    o: ["1", "3", "5", "7"],
    a: [3],
    e: "Les ports fiables sont ceux connectés aux serveurs DHCP légitimes ou aux commutateurs amont. Les ports des clients sont non fiables.",
  },
  {
    c: "wlan",
    q: "Quel mode de violation par défaut est utilisé lorsque la sécurité des ports est activée sans autre configuration ?",
    m: false,
    o: ["Protect", "Shutdown", "Restrict", "Désactivé"],
    a: [1],
    e: "Le mode de violation par défaut est Shutdown : lorsqu'une violation est détectée, l'interface est placée en état err-disabled.",
  },
  {
    c: "wlan",
    q: "Quelles sont les deux commandes permettant d'activer la protection BPDU à l'échelle globale ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "spanning-tree portfast bpduguard default",
      "spanning-tree bpduguard default",
      "enable spanning-tree bpduguard",
      "spanning-tree portfast bpduguard",
      "spanning-tree bpduguard enable",
    ],
    a: [0, 4],
    e: "spanning-tree portfast bpduguard default active BPDU Guard sur tous les ports PortFast. spanning-tree bpduguard enable l'active sur une interface spécifique.",
  },
  {
    c: "wlan",
    q: "Quelle configuration de sécurité des ports a permis la conservation des adresses MAC apprises dynamiquement après une panne d'alimentation ?",
    m: false,
    o: [
      "Adresses MAC sécurisées automatiques",
      "Adresses MAC sécurisées dynamiques",
      "Adresses MAC sécurisées statiques",
      "Adresses MAC sécurisées rémanentes (sticky)",
    ],
    a: [3],
    e: "Les adresses sticky sont apprises dynamiquement et enregistrées dans la configuration courante. Si sauvegardée en NVRAM, elles persistent après redémarrage.",
  },
  {
    c: "wlan",
    q: "Quel type d'antenne sans fil est le mieux adapté pour couvrir de grands espaces ouverts comme des couloirs ?",
    m: false,
    o: [
      "Omnidirectionnelle",
      "Yagi",
      "Directionnelle",
      "Parabolique",
    ],
    a: [0],
    e: "Une antenne omnidirectionnelle émet dans toutes les directions, ce qui la rend idéale pour couvrir de grands espaces ouverts uniformément.",
  },
  {
    c: "wlan",
    q: "Quelle topologie de réseau sans fil est utilisée pour fournir une connexion dans l'ensemble d'un bâtiment universitaire ?",
    m: false,
    o: ["Mode mixte", "Infrastructure", "Hotspot", "Ad hoc"],
    a: [1],
    e: "La topologie en mode infrastructure utilise des points d'accès (AP) connectés à l'infrastructure filaire pour couvrir une grande zone.",
  },
  {
    c: "wlan",
    q: "Quelles sont les deux normes 802.11 qui fonctionnent uniquement dans la gamme de fréquences 5 GHz ? (Choisissez deux réponses.)",
    m: true,
    o: ["802.11b", "802.11a", "802.11g", "802.11n", "802.11ac", "802.11ad"],
    a: [1, 4],
    e: "802.11a (jusqu'à 54 Mbps) et 802.11ac (jusqu'à plusieurs Gbps) fonctionnent uniquement en 5 GHz. Les autres standards utilisent aussi ou uniquement le 2,4 GHz.",
  },
  {
    c: "wlan",
    q: "À quoi sert la configuration du canal 1, 6 ou 11 sur un routeur sans fil 2,4 GHz ?",
    m: false,
    o: [
      "Activer différentes normes 802.11",
      "Désactiver la diffusion du SSID",
      "Fournir des modes de sécurité renforcés",
      "Éviter les interférences générées par des périphériques sans fil à proximité",
    ],
    a: [3],
    e: "Les canaux 1, 6 et 11 sont les seuls canaux non chevauchants en 2,4 GHz. Leur utilisation évite les interférences entre les réseaux sans fil adjacents.",
  },
  {
    c: "wlan",
    q: "Lorsqu'un présentateur tente de se connecter à un réseau sans fil, l'ordinateur portable n'affiche aucun réseau disponible. Quel mode du point d'accès empêche la diffusion passive du SSID ?",
    m: false,
    o: ["Actif", "Ouvert", "Passif", "Mixte"],
    a: [2],
    e: "En mode passif, le point d'accès diffuse régulièrement des trames beacon avec le SSID. Si la diffusion est désactivée, les clients ne voient pas le réseau.",
  },
  {
    c: "wlan",
    q: "Quelle est la première mesure de sécurité à prendre juste après avoir allumé un nouveau routeur sans fil ?",
    m: false,
    o: [
      "Désactiver la diffusion du SSID",
      "Changer le nom d'utilisateur et le mot de passe par défaut du routeur sans fil",
      "Activer le filtrage des adresses MAC",
      "Configurer le chiffrement",
    ],
    a: [1],
    e: "Les identifiants par défaut sont connus et publiés. Il faut les modifier en priorité pour empêcher tout accès non autorisé à l'interface d'administration.",
  },
  {
    c: "wlan",
    q: "Sur le tableau de bord du Cisco 3504 WLC, quelle option fournit l'accès au menu complet des fonctionnalités ?",
    m: false,
    o: ["Avancé", "Points d'accès", "Espions", "Résumé du réseau"],
    a: [0],
    e: "L'option 'Avancé' (Advanced) du WLC Cisco 3504 donne accès à tous les menus de configuration complets.",
  },
  {
    c: "wlan",
    q: "Quel onglet de la page récapitulative du WLC permet de configurer un WLAN avec une option de sécurité telle que WPA2 ?",
    m: false,
    o: ["WLAN", "SÉCURITÉ", "GESTION", "SANS FIL"],
    a: [0],
    e: "L'onglet WLAN du contrôleur permet de créer et de configurer les réseaux sans fil, y compris les paramètres de sécurité WPA2.",
  },
  {
    c: "wlan",
    q: "Quel service réseau permet de hiérarchiser le trafic pour s'assurer que la voix et la vidéo sont prioritaires sur les e-mails et les données Web ?",
    m: false,
    o: ["NAT", "QoS", "DNS", "DHCP"],
    a: [1],
    e: "La QoS (Quality of Service) permet de prioriser certains types de trafic (voix, vidéo) sur d'autres (e-mail, HTTP) pour garantir une bonne qualité.",
  },
  {
    c: "wlan",
    q: "Pourquoi la configuration d'un SSID en bande 5 GHz pour les services de streaming améliore-t-elle les performances ?",
    m: false,
    o: [
      "Seuls les utilisateurs avec des NIC récents peuvent accéder, réduisant l'utilisation globale",
      "La bande 5 GHz a une portée plus étendue et moins d'interférences",
      "La bande 5 GHz comprend plusieurs canaux et est moins encombrée que la bande 2,4 GHz",
      "Cela force les utilisateurs à basculer, réduisant le nombre d'utilisateurs qui accèdent aux services",
    ],
    a: [2],
    e: "La bande 5 GHz offre plus de canaux non chevauchants et est moins sujette aux interférences, ce qui améliore les performances pour le streaming.",
  },
  {
    c: "wlan",
    q: "Quel est le but du mot de passe secret partagé lors de la configuration d'un serveur RADIUS sur un WLC ?",
    m: false,
    o: [
      "Il est utilisé pour chiffrer les messages entre le WLC et le serveur RADIUS",
      "Il sert à authentifier les utilisateurs WLAN",
      "Il chiffre les données utilisateur sur le WLAN",
      "Il permet aux utilisateurs d'accéder au réseau",
    ],
    a: [0],
    e: "Le secret partagé (shared secret) est utilisé pour authentifier le WLC auprès du serveur RADIUS et chiffrer les messages RADIUS entre eux.",
  },
  {
    c: "wlan",
    q: "Quel composant AAA indique le succès ou l'échec d'une demande de service avec un message PASS ou FAIL ?",
    m: false,
    o: ["Gestion des comptes", "802.1X", "Authentification", "Autorisation"],
    a: [2],
    e: "L'authentification vérifie l'identité de l'utilisateur (nom d'utilisateur/mot de passe) et répond par PASS ou FAIL.",
  },
  {
    c: "wlan",
    q: "Quels sont les WLAN qui sont basés sur la norme 802.11 et fonctionnent sur les fréquences 2,4 GHz ou 5 GHz ?",
    m: false,
    o: [
      "Réseau étendu sans fil (WAN sans fil)",
      "Réseau métropolitain sans fil",
      "WLAN (réseau local sans fil)",
      "Réseau personnel sans fil (WPAN)",
    ],
    a: [2],
    e: "Les WLAN (802.11) fonctionnent dans les gammes 2,4 GHz et 5 GHz avec des portées de quelques dizaines à quelques centaines de mètres.",
  },
  {
    c: "wlan",
    q: "Quelles sont les deux solutions Cisco permettant de prévenir les attaques par épuisement de ressources DHCP ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Sécurité des ports (Port Security)",
      "Protection de la source IP (IP Source Guard)",
      "Espionnage DHCP (DHCP Snooping)",
      "Inspection ARP dynamique (DAI)",
      "Appliances de sécurisation Web",
    ],
    a: [1, 2],
    e: "IP Source Guard et DHCP Snooping permettent de limiter les requêtes DHCP et de valider les adresses IP sources, prévenant les attaques d'épuisement.",
  },
  {
    c: "wlan",
    q: "Citez trois actions permettant de pallier une attaque de saut de VLAN. (Choisissez trois réponses.)",
    m: true,
    o: [
      "Faire d'un VLAN inutilisé le VLAN natif",
      "Désactiver le protocole DTP sur les ports d'accès",
      "Activer manuellement le trunking sur les liaisons appropriées",
      "Activer la protection BPDU",
      "Activer la protection de source IP",
      "Utiliser des VLAN privés",
    ],
    a: [0, 1, 2],
    e: "Pour prévenir les attaques VLAN : utiliser un VLAN natif dédié et inutilisé, désactiver DTP sur les ports utilisateurs et configurer les trunks manuellement.",
  },
  {
    c: "wlan",
    q: "Reportez-vous à l'illustration. Que peut-on conclure à propos de la sécurité des ports d'après les informations affichées ?",
    m: false,
    o: [
      "Le port est désactivé",
      "Le port possède le nombre maximal d'adresses MAC autorisées",
      "Deux périphériques sont connectés au port",
      "Le mode de violation est le mode par défaut (shutdown)",
    ],
    a: [3],
    e: "Sans configuration explicite du mode de violation, le commutateur utilise le mode par défaut qui est 'shutdown' (err-disabled).",
  },
  {
    c: "wlan",
    q: "Quel est le serveur qui fournit l'authentification des utilisateurs WLAN via nom d'utilisateur et mot de passe ?",
    m: false,
    o: ["AAA", "SNMP", "NAT", "RADIUS"],
    a: [3],
    e: "Le serveur RADIUS (Remote Authentication Dial-In User Service) centralise l'authentification des utilisateurs sans fil via 802.1X.",
  },
  {
    c: "wlan",
    q: "Comment résoudre le problème de lenteur du réseau sans fil après le déploiement d'un routeur 802.11n/ac sur un réseau existant avec des appareils 802.11b/g ?",
    m: false,
    o: [
      "Modifier le SSID du routeur",
      "Configurer les appareils pour utiliser un autre canal",
      "Mettre à jour le firmware du routeur",
      "Diviser le trafic sans fil entre la bande 802.11n 2,4 GHz et la bande 5 GHz",
    ],
    a: [3],
    e: "Séparer les appareils lents (2,4 GHz) des appareils rapides (5 GHz) évite que les appareils anciens ralentissent l'ensemble du réseau.",
  },
  {
    c: "wlan",
    q: "Quel risque lié à la sécurité des réseaux sans fil essaie-t-on d'éviter en interdisant l'utilisation de fours à micro-ondes au bureau ?",
    m: false,
    o: [
      "Les interférences accidentelles",
      "Les points d'accès indésirables",
      "La configuration incorrecte des appareils",
      "L'interception de données",
    ],
    a: [0],
    e: "Les fours à micro-ondes émettent des ondes à 2,4 GHz et peuvent créer des interférences avec les réseaux WiFi opérant sur cette même fréquence.",
  },
  {
    c: "wlan",
    q: "Quelle est la fonction fournie par le protocole CAPWAP dans les réseaux sans fil d'entreprise ?",
    m: false,
    o: [
      "Il chiffre le trafic utilisateur sans fil",
      "Il crée un tunnel TCP pour la configuration des points d'accès",
      "Il encapsule et transfère le trafic utilisateur sans fil entre les AP et le contrôleur sans fil",
      "Il fournit une connectivité IPv6 et IPv4",
    ],
    a: [2],
    e: "CAPWAP (Control And Provisioning of Wireless Access Points) encapsule le trafic 802.11 dans des tunnels UDP entre les AP légers et le contrôleur WLC.",
  },
  {
    c: "wlan",
    q: "Reportez-vous à l'illustration. Que se passe-t-il s'il y a une violation de sécurité de port sur l'interface Fa 0/1 configurée en mode protect ?",
    m: false,
    o: [
      "Un message syslog est enregistré dans le journal",
      "Les paquets dont les adresses source sont inconnues sont abandonnés silencieusement",
      "Une notification est envoyée à l'administrateur",
      "L'interface est placée en état d'erreur (err-disabled)",
    ],
    a: [1],
    e: "En mode protect, les paquets avec des adresses MAC non autorisées sont simplement abandonnés sans notification ni incrémentation du compteur de violations.",
  },
  {
    c: "wlan",
    q: "Quel composant AAA vérifie quelles actions des utilisateurs sont effectuées sur le réseau ?",
    m: false,
    o: ["Autorisation", "802.1X", "Authentification", "Gestion des comptes"],
    a: [3],
    e: "La gestion des comptes (Accounting) enregistre les activités des utilisateurs sur le réseau pour des fins d'audit et de facturation.",
  },
  {
    c: "wlan",
    q: "Quels sont les trois paramètres à modifier en priorité pour sécuriser un point d'accès domestique ? (Choisissez trois réponses.)",
    m: true,
    o: [
      "Mot de passe du réseau sans fil",
      "Mot de passe du système d'exploitation client",
      "Mot de passe d'administration du point d'accès",
      "Heure d'émission des trames beacon",
      "Fréquence de l'antenne",
      "SSID (nom du réseau)",
    ],
    a: [0, 2, 5],
    e: "Il faut changer : le SSID par défaut (identifiable par marque), le mot de passe admin du routeur et le mot de passe du réseau WiFi.",
  },
  {
    c: "wlan",
    q: "Quelles sont les deux premières étapes de dépannage lorsqu'un ordinateur portable ne peut pas se connecter à un point d'accès sans fil ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "S'assurer que le SSID sans fil correct est sélectionné",
      "S'assurer que le support réseau correct est sélectionné",
      "S'assurer que la carte réseau sans fil est activée",
      "S'assurer que la fréquence de la carte est correctement configurée",
      "S'assurer que l'antenne est correctement fixée",
    ],
    a: [0, 2],
    e: "Les deux premières vérifications sont : que la carte WiFi est activée et que le bon SSID est sélectionné avant d'investiguer d'autres paramètres.",
  },
  {
    c: "wlan",
    q: "Quel est le protocole réseau qui peut surveiller les périphériques du réseau et envoyer des alertes aux administrateurs ?",
    m: false,
    o: ["SNMP", "RADIUS", "DHCP", "AAA"],
    a: [0],
    e: "SNMP (Simple Network Management Protocol) permet de surveiller et de gérer les équipements réseau, et d'envoyer des trappes (alertes) aux systèmes de gestion.",
  },
  {
    c: "wlan",
    q: "Quelle est la façon la plus simple de partager le trafic sans fil sur un routeur double bande (dual-band) ?",
    m: false,
    o: [
      "Ajouter un répéteur Wi-Fi sur des bandes différentes",
      "Vérifier et mettre à jour le firmware du routeur",
      "Exiger que tous les périphériques utilisent le standard 802.11n",
      "S'assurer que différents SSID sont utilisés pour les bandes 2,4 GHz et 5 GHz",
    ],
    a: [3],
    e: "Utiliser des SSID différents pour chaque bande permet aux utilisateurs de choisir la bande appropriée et d'équilibrer la charge entre 2,4 GHz et 5 GHz.",
  },
  {
    c: "wlan",
    q: "Quel est le type de réseau sans fil conçu pour les communications nationales et mondiales ?",
    m: false,
    o: [
      "Réseau métropolitain sans fil",
      "Réseau personnel sans fil (WPAN)",
      "Réseau étendu sans fil (WAN sans fil)",
      "WLAN",
    ],
    a: [2],
    e: "Les WAN sans fil (réseaux cellulaires, satellites) couvrent des zones géographiques larges à l'échelle nationale et internationale.",
  },
  {
    c: "wlan",
    q: "Quelle fonctionnalité d'un commutateur le rend vulnérable aux attaques à double étiquetage VLAN (VLAN double tagging) ?",
    m: false,
    o: [
      "Le VLAN natif du port trunk étant identique à celui d'un VLAN utilisateur",
      "La taille limitée de l'espace mémoire adressable",
      "Le mode duplex mixte activé par défaut",
      "La fonctionnalité de liaison automatique des ports activée par défaut",
    ],
    a: [0],
    e: "Si le VLAN natif du trunk est le même que celui d'un utilisateur, un pirate peut encapsuler une trame dans une autre trame VLAN pour l'envoyer dans un VLAN non autorisé.",
  },
  {
    c: "wlan",
    q: "Quel est l'un des avantages du masquage du SSID ?",
    m: false,
    o: [
      "C'est la meilleure façon de sécuriser un réseau sans fil",
      "Les SSID masqués sont très difficiles à détecter même sans diffusion",
      "Les clients devront identifier manuellement le SSID pour se connecter au réseau",
      "Cela fournit un accès Internet gratuit aux utilisateurs publics",
    ],
    a: [2],
    e: "Masquer le SSID oblige les clients à entrer manuellement le nom du réseau. Ce n'est pas une mesure de sécurité forte, car le SSID reste détectable.",
  },
  {
    c: "wlan",
    q: "Quelle norme sans fil prend en charge des débits allant jusqu'à 1,3 Gbit/s tout en maintenant la rétrocompatibilité ?",
    m: false,
    o: ["802.11b", "802.11n", "802.11ac", "802.11g"],
    a: [2],
    e: "802.11ac (Wi-Fi 5) fonctionne uniquement en 5 GHz et atteint plusieurs Gbps. Il est rétrocompatible avec 802.11a.",
  },
  {
    c: "wlan",
    q: "Quelles sont les deux méthodes qu'un hôte sans fil peut utiliser pour découvrir un point d'accès ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Transmission d'une requête d'analyse (probe request)",
      "Envoi d'une trame de diffusion",
      "Réception d'une trame de balise de diffusion (beacon frame)",
      "Établissement d'une connexion TCP en trois étapes",
      "Envoi d'une requête ARP",
    ],
    a: [0, 2],
    e: "Le mode actif utilise une probe request pour trouver des AP. Le mode passif attend de recevoir les trames beacon diffusées régulièrement par l'AP.",
  },
  {
    c: "wlan",
    q: "Reportez-vous à l'illustration. Quelle action se produira lorsque PC1 sera connecté à l'interface Fa 0/12 avec la configuration de sécurité de port appliquée ?",
    m: false,
    o: [
      "Les trames de PC1 seront transférées et aucun journal ne sera créé",
      "Les trames de PC1 seront transférées et un journal sera créé",
      "Les trames de PC1 seront supprimées et un journal sera créé",
      "Les trames de PC1 seront transférées (commande violation manquante)",
      "Les trames de PC1 seront supprimées et aucun journal ne sera créé",
      "L'interface sera immédiatement arrêtée et un journal sera créé",
    ],
    a: [5],
    e: "Avec le mode de violation par défaut (shutdown), si l'adresse MAC de PC1 ne correspond pas, l'interface est immédiatement désactivée et un journal est enregistré.",
  },
  {
    c: "wlan",
    q: "Quel type d'attaque par saut de VLAN peut être prévenu en définissant un VLAN inutilisé comme VLAN natif ?",
    m: false,
    o: [
      "Attaque à double étiquetage VLAN (double tagging)",
      "Usurpation DHCP (DHCP spoofing)",
      "Épuisement de ressources DHCP",
      "Usurpation DTP (DTP spoofing)",
    ],
    a: [0],
    e: "L'attaque double tagging exploite le fait que le commutateur retire la première étiquette VLAN (natif). En utilisant un VLAN natif inutilisé, on neutralise cette attaque.",
  },
  {
    c: "wlan",
    q: "Quel est l'objectif de la commande ip arp inspection validate src-mac ?",
    m: false,
    o: [
      "Elle vérifie l'adresse MAC source dans l'en-tête Ethernet par rapport aux ACL utilisateur",
      "Elle vérifie l'adresse MAC source par rapport à l'adresse MAC cible dans la réponse ARP",
      "Elle vérifie l'adresse MAC source dans l'en-tête Ethernet par rapport à l'adresse MAC expéditeur dans l'en-tête ARP",
      "Elle vérifie l'adresse MAC source par rapport à la table d'adresses MAC",
    ],
    a: [2],
    e: "ip arp inspection validate src-mac vérifie que l'adresse MAC source de l'en-tête Ethernet correspond au champ MAC expéditeur du paquet ARP, détectant les attaques ARP.",
  },
  {
    c: "wlan",
    q: "Quel mode de violation doit être configuré pour supprimer les paquets des adresses source inconnues sans envoyer de notification ?",
    m: false,
    o: ["Off", "Restrict", "Protect", "Shutdown"],
    a: [2],
    e: "Le mode protect supprime silencieusement les paquets non autorisés sans journalisation ni notification. Le mode restrict enregistre les violations.",
  },
  {
    c: "wlan",
    q: "Quel est l'avantage en matière de sécurité de la protection BPDU sur les interfaces PortFast ?",
    m: false,
    o: [
      "Elle renforce la mise en place correcte du pont racine (root bridge)",
      "Elle empêche les attaques par saturation de la mémoire tampon",
      "Elle protège contre les boucles de couche 2",
      "Elle empêche l'ajout de commutateurs non fiables au réseau",
    ],
    a: [3],
    e: "BPDU Guard désactive les ports PortFast si des BPDU sont reçus, empêchant un commutateur non autorisé de perturber la topologie STP.",
  },
  {
    c: "wlan",
    q: "Quel est l'effet de la commande ip dhcp snooping limit rate 6 appliquée aux interfaces Fa0/5 à Fa0/10 ?",
    m: false,
    o: [
      "Si plus de 6 messages DHCP par seconde sont reçus, le port s'arrête",
      "Si plus de 6 messages DHCP par seconde sont reçus, le port continue mais une erreur est envoyée",
      "Les ports peuvent recevoir jusqu'à 6 messages DHCP par seconde quelconques",
      "Les ports peuvent recevoir jusqu'à 6 messages DHCP Discovery par seconde",
    ],
    a: [0],
    e: "ip dhcp snooping limit rate limite le taux de messages DHCP. Si le débit dépasse la limite, le port est désactivé (err-disabled) pour bloquer les attaques.",
  },
  {
    c: "wlan",
    q: "Quel protocole doit être utilisé pour atténuer la vulnérabilité de sécurité de la gestion à distance via Telnet ?",
    m: false,
    o: ["SNMP", "SSH", "TFTP", "SCP"],
    a: [1],
    e: "SSH chiffre toutes les communications, contrairement à Telnet qui transmet les données en clair. SSH remplace avantageusement Telnet pour l'administration à distance.",
  },
  {
    c: "wlan",
    q: "Quel composant du modèle AAA détermine les ressources réseau auxquelles un utilisateur peut accéder et les opérations qu'il peut effectuer ?",
    m: false,
    o: ["Traçabilité", "Audit", "Authentification", "Autorisation"],
    a: [3],
    e: "L'autorisation (Authorization) détermine ce qu'un utilisateur authentifié est autorisé à faire : quelles commandes il peut exécuter, quelles ressources il peut accéder.",
  },
  {
    c: "wlan",
    q: "Quel type de trame de gestion est régulièrement diffusé par un point d'accès pour annoncer sa présence ?",
    m: false,
    o: [
      "Réponse d'analyse (probe response)",
      "Authentification",
      "Requête d'analyse (probe request)",
      "Balise (beacon)",
    ],
    a: [3],
    e: "Les trames beacon sont diffusées périodiquement par les AP (généralement 10 fois par seconde) pour annoncer le SSID et les capacités du réseau.",
  },
  {
    c: "wlan",
    q: "Quelle est la meilleure méthode pour améliorer les performances d'un réseau sans fil 802.11n qui se dégrade ?",
    m: false,
    o: [
      "Mettre à niveau le firmware du point d'accès",
      "Désactiver DHCP et attribuer des adresses statiques à tous les clients",
      "Répartir le trafic sans fil entre les bandes de fréquences 2,4 GHz et 5 GHz",
      "Remplacer les cartes réseau sans fil des clients",
    ],
    a: [2],
    e: "Déplacer les clients rapides vers la bande 5 GHz et laisser les anciens appareils sur 2,4 GHz améliore les performances en évitant les conflits de vitesse.",
  },
  {
    c: "wlan",
    q: "Quel service permet aux ordinateurs portables recevant des adresses du réseau 10.0.10.0/24 d'accéder à Internet ?",
    m: false,
    o: ["RADIUS", "NAT", "DNS", "DHCP"],
    a: [1],
    e: "NAT (Network Address Translation) traduit les adresses privées en adresses publiques pour permettre l'accès à Internet.",
  },
  {
    c: "wlan",
    q: "Quel composant AAA enregistre les commandes EXEC et de configuration exécutées par les utilisateurs ?",
    m: false,
    o: [
      "Authentification",
      "Autorisation",
      "802.1X",
      "Gestion des comptes (Accounting)",
    ],
    a: [3],
    e: "La gestion des comptes (Accounting) enregistre toutes les actions des utilisateurs, y compris les commandes exécutées, pour l'audit et la conformité.",
  },
  {
    c: "wlan",
    q: "Quel est le type de réseau sans fil conçu pour une utilisation à la maison ou dans un bureau de petite taille ?",
    m: false,
    o: [
      "Réseau métropolitain sans fil",
      "WLAN",
      "Réseau étendu sans fil (WAN sans fil)",
      "Réseau personnel sans fil (WPAN)",
    ],
    a: [1],
    e: "Les WLAN (Wi-Fi) sont conçus pour les environnements de petite et moyenne taille comme les maisons, les bureaux et les campus.",
  },
  {
    c: "wlan",
    q: "Quels sont les deux protocoles permettant à AAA d'authentifier les utilisateurs par rapport à une base de données centralisée de noms d'utilisateurs et de mots de passe ? (Choisissez deux réponses.)",
    m: true,
    o: ["NTP", "SSH", "TACACS+", "RADIUS", "CHAP", "HTTPS"],
    a: [2, 3],
    e: "TACACS+ (Cisco propriétaire) et RADIUS (standard ouvert) sont les deux principaux protocoles utilisés pour l'authentification AAA centralisée.",
  },
  {
    c: "wlan",
    q: "Quelle caractéristique d'un commutateur le rend vulnérable aux attaques par saut de VLAN ?",
    m: false,
    o: [
      "La fonctionnalité de port de liaison automatique activée par défaut (auto trunking)",
      "La prise en charge de bandes passantes mixtes sur les ports",
      "Le mode duplex mixte activé par défaut",
      "La taille limitée de la mémoire adressable",
    ],
    a: [0],
    e: "Si le port est en mode DTP auto, un attaquant peut envoyer des trames DTP pour négocier un trunk et accéder à tous les VLAN (VLAN hopping).",
  },
  {
    c: "wlan",
    q: "Quel composant AAA contrôle les actions que les utilisateurs sont autorisés à réaliser sur le réseau ?",
    m: false,
    o: [
      "802.1X",
      "Gestion des comptes",
      "Autorisation",
      "Authentification",
    ],
    a: [2],
    e: "L'autorisation contrôle les droits d'accès : quelles interfaces l'utilisateur peut configurer, quelles commandes il peut exécuter.",
  },
  {
    c: "wlan",
    q: "Quel est le type de réseau sans fil qui utilise couramment les technologies Bluetooth ou ZigBee ?",
    m: false,
    o: [
      "WLAN",
      "Réseau étendu sans fil (WAN sans fil)",
      "Réseau métropolitain sans fil",
      "Réseau personnel sans fil (WPAN)",
    ],
    a: [3],
    e: "Les WPAN (réseaux personnels sans fil) utilisent des technologies comme Bluetooth, ZigBee ou NFC avec une portée de quelques mètres.",
  },
  {
    c: "wlan",
    q: "Quel mode de sécurité sans fil requiert un serveur RADIUS pour l'authentification des utilisateurs ?",
    m: false,
    o: ["Personnel", "Entreprise", "WEP", "Clé partagée"],
    a: [1],
    e: "Le mode entreprise (WPA2-Enterprise) utilise 802.1X et un serveur RADIUS pour authentifier chaque utilisateur individuellement avec un nom et mot de passe.",
  },
  {
    c: "wlan",
    q: "Quelle est la meilleure pratique concernant les protocoles CDP et LLDP de découverte de voisins ?",
    m: false,
    o: [
      "Activer CDP sur les périphériques de bord et LLDP sur les périphériques intérieurs",
      "Utiliser LLDP (standard ouvert) plutôt que CDP (propriétaire Cisco)",
      "Utiliser les paramètres par défaut du routeur",
      "Désactiver les deux protocoles sur toutes les interfaces où ils ne sont pas requis",
    ],
    a: [3],
    e: "CDP et LLDP peuvent divulguer des informations sensibles sur les équipements réseau. Il est préférable de les désactiver là où ils ne sont pas nécessaires.",
  },
  {
    c: "wlan",
    q: "Quelle étape est requise avant de créer un nouveau WLAN sur un WLC Cisco 3500 ?",
    m: false,
    o: [
      "Créer et provisionner un serveur SNMP",
      "Créer et provisionner un serveur RADIUS",
      "Créer un nouveau SSID",
      "Créer une nouvelle interface de VLAN",
    ],
    a: [3],
    e: "Sur un WLC, il faut d'abord créer une interface VLAN qui servira de segment réseau pour le nouveau WLAN avant de pouvoir créer le WLAN.",
  },
  {
    c: "wlan",
    q: "Quel type de réseau sans fil utilise des appareils montés sur les bâtiments pour couvrir une ville ?",
    m: false,
    o: [
      "Réseau personnel sans fil (WPAN)",
      "WLAN",
      "Réseau étendu sans fil (WAN sans fil)",
      "Réseau métropolitain sans fil (WMAN)",
    ],
    a: [3],
    e: "Les réseaux métropolitains sans fil (WMAN) utilisent des antennes montées sur des bâtiments pour couvrir des zones urbaines entières (plusieurs kilomètres).",
  },
  {
    c: "wlan",
    q: "Quel composant AAA restreint l'accès au réseau par les ports publics d'un commutateur ?",
    m: false,
    o: ["Autorisation", "802.1X", "Authentification", "Gestion des comptes"],
    a: [1],
    e: "802.1X est le standard IEEE qui contrôle l'accès réseau par port. Il utilise le mécanisme EAP pour authentifier les utilisateurs avant de leur autoriser l'accès.",
  },
  {
    c: "wlan",
    q: "Quel type de réseau sans fil utilise des transmetteurs pour fournir une couverture sans fil sur une zone géographique étendue ?",
    m: false,
    o: [
      "Réseau étendu sans fil (WAN sans fil)",
      "Réseau métropolitain sans fil",
      "Réseau personnel sans fil (WPAN)",
      "WLAN",
    ],
    a: [0],
    e: "Les WAN sans fil (réseaux cellulaires 3G/4G/5G) utilisent un réseau d'antennes relais pour couvrir de larges zones géographiques.",
  },
  {
    c: "wlan",
    q: "Quel composant AAA est basé sur les rôles de demandeur (supplicant), d'authentificateur et de serveur d'authentification ?",
    m: false,
    o: [
      "Gestion des comptes",
      "Authentification",
      "802.1X",
      "Autorisation",
    ],
    a: [2],
    e: "802.1X définit une architecture avec trois rôles : le supplicant (client), l'authenticator (commutateur/AP) et le serveur d'authentification (RADIUS).",
  },
  {
    c: "wlan",
    q: "Quel composant AAA est basé sur la vérification des noms d'utilisateur et des mots de passe ?",
    m: false,
    o: [
      "Authentification",
      "802.1X",
      "Autorisation",
      "Gestion des comptes",
    ],
    a: [0],
    e: "L'authentification est le processus de vérification de l'identité d'un utilisateur, généralement par un nom d'utilisateur et un mot de passe.",
  },
  {
    c: "wlan",
    q: "Quel composant AAA contrôle qui est autorisé à accéder au réseau en vérifiant l'identité ?",
    m: false,
    o: [
      "Authentification",
      "802.1X",
      "Autorisation",
      "Gestion des comptes",
    ],
    a: [0],
    e: "L'authentification vérifie l'identité de l'utilisateur (qui êtes-vous ?) avant d'autoriser l'accès au réseau.",
  },
  {
    c: "wlan",
    q: "Quel type de réseau sans fil utilise des émetteurs basse puissance avec une portée de 6 à 9 mètres ?",
    m: false,
    o: [
      "Réseau personnel sans fil (WPAN)",
      "WLAN",
      "Réseau étendu sans fil (WAN sans fil)",
      "Réseau métropolitain sans fil",
    ],
    a: [0],
    e: "Les WPAN (comme Bluetooth) utilisent des émetteurs basse puissance couvrant quelques mètres, idéals pour connecter des appareils personnels proches.",
  },
  {
    c: "wlan",
    q: "Quel type de réseau sans fil utilise des émetteurs pour couvrir une grande région urbaine ?",
    m: false,
    o: [
      "Réseau personnel sans fil (WPAN)",
      "WLAN",
      "Réseau métropolitain sans fil (WMAN)",
      "Réseau étendu sans fil (WAN sans fil)",
    ],
    a: [2],
    e: "Les réseaux métropolitains sans fil (WMAN) couvrent des zones urbaines entières, souvent en utilisant WiMAX ou des technologies similaires.",
  },
];
