const QUESTIONS_5_6 = [
        {
          c: "stp",
          q: "Quels sont les trois composants qui sont combinés pour former un ID de pont ?",
          m: true,
          o: [
            "Coût",
            "ID système étendu",
            "Adresse IP",
            "ID de port",
            "Priorité du pont",
            "Adresse MAC",
          ],
          a: [1, 4, 5],
          e: "Les 3 composants sont : priorité du pont + ID système étendu + adresse MAC.",
        },
        {
          c: "stp",
          q: "Quels sont les deux états de port dans lesquels un commutateur apprend les adresses MAC et traite les trames BPDU sur un réseau PVST ? (Choisissez deux réponses.)",
          m: true,
          o: [
            "blocage",
            "transmission",
            "désactivé",
            "écoute",
            "apprentissage",
          ],
          a: [1, 4],
          e: "Les adresses MAC sont apprises aux états de transmission et d'apprentissage.",
        },
        {
          c: "stp",
          q: "Si aucune priorité de pont n’est configurée dans le protocole PVST, quels critères sont pris en considération lors de la sélection du pont racine ?",
          m: false,
          o: [
            "adresse IP la plus élevée",
            "adresse MAC la plus élevée",
            "adresse MAC la plus petite",
            "adresse IP la plus petite",
          ],
          a: [2],
          e: "Sans priorité configurée, tous utilisent la valeur par défaut, et la plus petite adresse MAC détermine le pont racine.",
        },
        {
          c: "stp",
          q: "Quelles sont les deux fonctionnalités de conception de réseau qui nécessitent le protocole STP (Spanning Tree Protocol) pour assurer un fonctionnement correct du réseau ? (Choisissez deux réponses.)",
          m: true,
          o: [
            "routes par défaut statiques",
            "implémentation de VLAN pour contenir des diffusions",
            "liaisons redondantes entre des commutateurs de couche 2",
            "routages dynamiques à état de liens fournissant des routes redondantes",
            "suppression de points de défaillance uniques avec plusieurs commutateurs de couche 2",
          ],
          a: [2, 4],
          e: "STP est nécessaire pour les liaisons redondantes entre commutateurs de couche 2 et pour éliminer les points de défaillance uniques.",
        },
        {
          c: "stp",
          q: "Quel est le résultat d’une tempête de diffusion de couche 2 ?",
          m: false,
          o: [
            "CSMA/CD amène chaque hôte à transmettre des trames.",
            "Les requêtes ARP sont renvoyées à l'hôte émetteur.",
            "Les routeurs prennent le relais pour l'acheminement des trames.",
            "Le nouveau trafic est rejeté par le commutateur car il ne peut pas être traité.",
          ],
          a: [3],
          e: "Quand le réseau est saturé par des diffusions en boucle, tout nouveau trafic est rejeté car il ne peut pas être traité.",
        },
        {
          c: "stp",
          q: "Associez le protocole STP à la description correcte. (Les options ne doivent pas être toutes utilisées.)",
          m: false,
          i: "2022-06-27_120527.jpg",
          o: [
            "STP=original 802.1D, PVST+=Cisco par VLAN, RSTP=convergence rapide 802.1w, Rapid PVST+=Cisco rapide par VLAN",
            "STP=rapide, PVST+=original, RSTP=Cisco, Rapid PVST+=standard",
            "PVST+=original, STP=Cisco, RSTP=rapide, Rapid PVST+=sans VLAN",
            "STP=multi-VLAN, PVST+=standard, RSTP=Cisco, Rapid PVST+=lent",
          ],
          a: [0],
          e: "STP=802.1D (original) / PVST+=Cisco par VLAN / RSTP=802.1w (convergence rapide) / Rapid PVST+=Cisco basé sur RSTP.",
        },
        {
          c: "stp",
          q: "Associez la fonctionnalité Spanning Tree au type de protocole. (Les options ne sont pas toutes utilisées.)",
          m: false,
          i: "2022-06-27_120742.jpg",
          o: [
            "MST=Cisco de MSTP (IEEE 802.1s) — PVST+=Cisco par VLAN — Rapid PVST+=Cisco sur RSTP",
            "MST=IEEE / PVST+=Cisco par VLAN / STP=Cisco",
            "MST=Cisco / PVST+=IEEE / RSTP=Cisco",
            "STP=MST / PVST+=IEEE / RSTP=Cisco",
          ],
          a: [0],
          e: "MST est l'implémentation Cisco de MSTP (IEEE 802.1s). PVST+ = Cisco par VLAN. Rapid PVST+ = Cisco basé sur RSTP.",
        },
        {
          c: "stp",
          q: "Lorsque la commande show spanning-tree vlan 33 est exécutée sur un commutateur, trois ports apparaissent en état de transmission. Quels sont les deux rôles de port dans lesquels ces interfaces peuvent fonctionner à partir de l’état de transmission ? (Choisissez deux réponses.)",
          m: true,
          o: ["alternatif", "désactivé", "bloqué", "désigné", "racine"],
          a: [3, 4],
          e: "Les ports en transmission sont soit port désigné soit port racine. Les ports en blocage sont alternatifs.",
        },
        {
          c: "stp",
          q: "Un ensemble de commutateurs est connecté au sein d’une topologie LAN. Quelle valeur de priorité de pont STP réduit la probabilité que le commutateur soit sélectionné en tant que racine ?",
          m: false,
          o: ["61440", "4096", "32768", "65535"],
          a: [0],
          e: "La priorité 61440 est la plus grande valeur valide (le plus petit numéro est préféré pour le pont racine).",
        },
        {
          c: "stp",
          q: "Quelle est la fonction du protocole STP dans un réseau évolutif ?",
          m: false,
          o: [
            "Il combine plusieurs trunks sous forme de liaison logique unique.",
            "Il protège la périphérie du réseau contre les actions malveillantes.",
            "Il désactive les chemins redondants pour éliminer les boucles de couche 2.",
            "Il réduit la taille du domaine défaillant.",
          ],
          a: [2],
          e: "Le STP désactive les chemins redondants qui créeraient des boucles de couche 2.",
        },
        {
          c: "stp",
          q: "À quoi sert le protocole STP (Spanning Tree Protocol) ?",
          m: false,
          o: [
            "À empêcher les boucles de couche 2",
            "À créer des domaines de diffusion plus petits",
            "À empêcher les boucles de routage sur un routeur",
            "À créer des domaines de collision plus petits",
            "À permettre aux appareils Cisco d'échanger des mises à jour de routage",
          ],
          a: [0],
          e: "Le STP crée un chemin libre de boucles à travers un réseau commuté de couche 2.",
        },
        {
          c: "stp",
          q: "Quels sont les deux états de ports PVST+ permettant l’apprentissage des adresses MAC ? Citez-en deux.",
          m: true,
          o: [
            "Transmission",
            "en apprentissage",
            "Écoute",
            "désactivé",
            "Blocage",
          ],
          a: [0, 1],
          e: "Les adresses MAC sont apprises et ajoutées à la table aux états apprentissage et transmission.",
        },
        {
          c: "stp",
          q: "Reportez-vous à l’illustration. Quel commutateur sera le pont racine au terme du processus de sélection ?",
          m: false,
          i: "2022-06-27_121112.jpg",
          o: ["S1", "S2", "S3", "S4"],
          a: [1],
          e: "Toutes les priorités sont identiques. L'adresse MAC la plus basse désigne le pont racine — c'est S2.",
        },
        {
          c: "stp",
          q: "Quels sont les deux inconvénients que présentent la désactivation de Spanning Tree et l’utilisation de plusieurs chemins sur le réseau commuté de couche 2 ? (Choisissez deux propositions.)",
          m: true,
          o: [
            "Le système de sécurité des ports arrête tous les ports reliés.",
            "Le commutateur joue le rôle de hub.",
            "Des trames de diffusion sont transmises indéfiniment.",
            "La sécurité des ports devient instable.",
            "La table des adresses MAC devient instable.",
          ],
          a: [2, 4],
          e: "Sans STP : la table MAC devient instable et des tempêtes de diffusion peuvent rendre le réseau inutilisable.",
        },
        {
          c: "stp",
          q: "Parmi les affirmations concernant l’utilisation du protocole PAgP pour créer des EtherChannels, laquelle est correcte ?",
          m: false,
          o: [
            "Il requiert davantage de liaisons physiques que LACP.",
            "Il rend obligatoire l'utilisation d'un nombre pair de ports.",
            "Il augmente le nombre de ports participant au Spanning Tree.",
            "Il requiert le mode bidirectionnel simultané.",
            "Il s'agit d'un protocole propriétaire Cisco.",
          ],
          a: [4],
          e: "PAgP est propriétaire Cisco. LACP est le standard ouvert équivalent. Un EtherChannel est vu comme un seul port par le STP.",
        },
        {
          c: "stp",
          q: "Citez deux conditions requises pour pouvoir configurer un EtherChannel entre deux commutateurs ? (Choisissez deux réponses.)",
          m: true,
          o: [
            "Toutes les interfaces doivent fonctionner dans le même mode bidirectionnel.",
            "Différentes plages autorisées de VLAN doivent exister à chaque extrémité.",
            "Les interfaces doivent être contiguës sur le commutateur.",
            "Toutes les interfaces doivent fonctionner à la même vitesse.",
            "Toutes les interfaces doivent être affectées à différents VLAN.",
          ],
          a: [0, 3],
          e: "Les interfaces d'un EtherChannel doivent avoir le même mode bidirectionnel et la même vitesse.",
        },
        {
          c: "stp",
          q: "Examinez l’illustration. D’après le résultat affiché, quelles conclusions pouvez-vous tirer à propos de la liaison EtherChannel ?",
          m: false,
          i: "2022-06-27_121214.jpg",
          o: [
            "La liaison EtherChannel est en panne.",
            "La liaison EtherChannel fonctionne sur les couches 2 et 3.",
            "Un protocole propriétaire Cisco a été utilisé pour négocier la liaison.",
            "Deux ports Gigabit Ethernet forment la liaison EtherChannel.",
          ],
          a: [2],
          e: "L'output montre que PAgP (protocole propriétaire Cisco) a été utilisé pour négocier la liaison EtherChannel.",
        },
        {
          c: "stp",
          q: "Quels sont les deux paramètres devant correspondre sur les ports des deux commutateurs afin de créer une liaison PAgP EtherChannel entre les commutateurs ? (Choisissez deux réponses.)",
          m: true,
          o: [
            "vitesse",
            "adresse MAC",
            "ID de port",
            "informations VLAN",
            "mode PAgP",
          ],
          a: [0, 3],
          e: "Pour créer un EtherChannel, les ports doivent correspondre en vitesse et informations VLAN.",
        },
        {
          c: "stp",
          q: "Examinez l’illustration. Un EtherChannel a été configuré entre les commutateurs S1 et S2, mais les interfaces ne forment pas d’EtherChannel. Quel est le problème ?",
          m: false,
          i: "2022-06-27_121308.jpg",
          o: [
            "Les ports n'ont pas été configurés avec le mode vitesse et bidirectionnel.",
            "L'EtherChannel n'a pas été configuré avec la même plage autorisée de VLAN sur chaque interface.",
            "Les ports doivent être configurés en ports d'accès avec un VLAN assigné.",
            "Le numéro interface port-channel doit être différent sur chaque commutateur.",
          ],
          a: [1],
          e: "Les interfaces d'un EtherChannel doivent prendre en charge la même plage autorisée de VLAN.",
        },
        {
          c: "stp",
          q: "Quel paramètre de configuration de mode autorise la formation d’une liaison EtherChannel entre les commutateurs SW1 et SW2 sans envoyer de trafic de négociation ?",
          m: false,
          o: [
            "SW1: auto / SW2: auto + PortFast activé",
            "SW1: desirable / SW2: desirable",
            "SW1: auto / SW2: auto + trunking activé",
            "SW1: on / SW2: on",
            "SW1: passive / SW2: active",
          ],
          a: [3],
          e: "Le mode 'on' force l'EtherChannel sans aucune négociation PAgP ni LACP.",
        },
        {
          c: "stp",
          q: "Citez deux modes de groupe de canaux plaçant une interface en état de négociation au moyen du protocole PAgP ? (Choisissez deux réponses.)",
          m: true,
          o: ["active", "passive", "auto", "on", "desirable"],
          a: [2, 4],
          e: "Les modes 'desirable' et 'auto' placent l'interface en état de négociation PAgP. 'active' et 'passive' sont pour LACP.",
        },
        {
          c: "stp",
          q: "Un administrateur réseau a configuré une liaison EtherChannel entre deux commutateurs par le biais de quatre liaisons trunk. Si l’interface physique pour l’une des liaisons trunk passe à l’état « down », qu’advient-il de l’EtherChannel ?",
          m: false,
          o: [
            "L'EtherChannel passera à l'état 'down'.",
            "Le STP recalculera les liaisons trunk restantes.",
            "Le STP fera passer l'interface défaillante en mode d'acheminement.",
            "L'EtherChannel restera fonctionnel.",
          ],
          a: [3],
          e: "EtherChannel assure la redondance. La perte d'une liaison physique ne modifie pas la topologie — l'EtherChannel reste fonctionnel.",
        },
        {
          c: "stp",
          q: "Reportez-vous à l’illustration. Un administrateur réseau est en train de configurer une liaison EtherChannel entre deux commutateurs, SW1 et SW2. Quelle instruction décrit l’effet après l’émission des commandes sur SW1 et SW2?",
          m: false,
          i: "2022-06-27_121413.jpg",
          o: [
            "L'EtherChannel est établi sans négociation.",
            "L'EtherChannel est établi après que SW1 initie la requête.",
            "L'EtherChannel est établi après que SW2 a lancé la requête.",
            "La liaison EtherChannel échoue.",
          ],
          a: [3],
          e: "SW1 est en mode 'on' et SW2 est en mode 'desirable' (PAgP). Ces modes sont incompatibles — la liaison EtherChannel échoue.",
        },
        {
          c: "stp",
          q: "Reportez-vous à l’illustration. Un administrateur réseau est en train de configurer une liaison EtherChannel entre deux commutateurs, SW1 et SW2. Toutefois, la liaison EtherChannel ne parvient pas à établir. Quel changement de configuration corrigerait le problème?",
          m: false,
          i: "2022-06-27_121516.jpg",
          o: [
            "Configurez SW2 EtherChannel sur activé.",
            "Configurez SW2 EtherChannel sur automatique.",
            "Configurez SW1 EtherChannel sur activé.",
            "Configurez SW2 EtherChannel sur souhaitable.",
          ],
          a: [3],
          e: "Modes PAgP compatibles : on/on, auto/desirable, desirable/desirable. SW2 doit être en mode 'desirable' pour fonctionner avec le mode 'auto' de SW1.",
        },
        {
          c: "stp",
          q: "Un administrateur réseau a configuré une liaison EtherChannel avec trois interfaces entre deux commutateurs. Que se passe-t-il si l’une des trois interfaces tombe en panne ?",
          m: false,
          o: [
            "L'une des interfaces devient active, l'autre devient de secours.",
            "Les deux interfaces restantes deviennent des liaisons distinctes.",
            "Les deux interfaces restantes continuent d'équilibrer le trafic.",
            "La liaison EtherChannel échoue.",
          ],
          a: [2],
          e: "EtherChannel est une liaison logique unique. La perte d'une liaison physique n'entraîne pas de modification de topologie — les autres interfaces équilibrent le trafic.",
        },
        {
          c: "stp",
          q: "Quelle est l’une des conditions requises pour configurer un trunk EtherChannel entre deux commutateurs ?",
          m: false,
          o: [
            "Les interfaces doivent être sur le même module sur un commutateur.",
            "Les interfaces doivent avoir le même numéro de VLAN sur les deux commutateurs.",
            "La plage de VLAN autorisés doit être identique sur les deux commutateurs.",
            "Les interfaces doivent être physiquement contiguës sur un commutateur.",
          ],
          a: [2],
          e: "La plage de VLAN autorisés doit être identique sur toutes les interfaces d'un trunk EtherChannel.",
        },
        {
          c: "stp",
          q: "Quelle est la description correcte d’une implémentation EtherChannel ?",
          m: false,
          o: [
            "PAgP ne peut pas être utilisé en même temps qu'EtherChannel.",
            "Un port de trunking peut faire partie d'un groupement EtherChannel.",
            "EtherChannel prend en charge jusqu'à dix liaisons distinctes.",
            "EtherChannel fonctionne uniquement au niveau de la couche 2.",
          ],
          a: [1],
          e: "Un port de trunking peut faire partie d'un groupement EtherChannel (tous les ports du groupement doivent alors être des ports trunking avec le même VLAN natif). EtherChannel prend jusqu'à 8 liens.",
        },
        {
          c: "stp",
          q: "Un commutateur est configuré pour exécuter STP. Quel terme décrit un champ utilisé pour spécifier un ID VLAN?",
          m: false,
          o: [
            "ID de pont",
            "ID de port",
            "Priorité du pont",
            "ID système étendu",
          ],
          a: [3],
          e: "L'ID système étendu (Extended System ID) est le champ utilisé dans STP pour spécifier l'ID VLAN.",
        },
        {
          c: "stp",
          q: "Reportez-vous à l’illustration. Quels sont les rôles possibles pour les ports A, B, C et D dans ce réseau RSTP ?",
          m: false,
          i: "2022-06-27_121604.jpg",
          o: [
            "Alternatif, désigné, racine, racine",
            "Désigné, racine, alternatif, racine",
            "Alternatif, racine, désigné, racine",
            "Désigné, alternatif, racine, racine",
          ],
          a: [0],
          e: "S1 est le pont racine. B=port désigné. C et D=ports racines. A=port alternatif (nouveau type RSTP).",
        },
        {
          c: "stp",
          q: "Examinez l’illustration. Quelle technologie de commutation autorise l’agrégation de chaque liaison de commutateur de couche d’accès afin de fournir davantage de bande passante entre chaque commutateur de couche 2 et le commutateur de couche 3 ?",
          m: false,
          i: "2022-06-27_121646.jpg",
          o: ["Trunking", "HSRP", "EtherChannel", "PortFast"],
          a: [2],
          e: "EtherChannel agrège plusieurs liaisons physiques en une seule connexion logique, augmentant la bande passante.",
        },
        {
          c: "stp",
          q: "Examinez l’illustration. Un administrateur souhaite établir un EtherChannel entre les deux commutateurs en utilisant le protocole PAgP (Port Aggregation Protocol) . Si le commutateur S1 est configuré pour être en mode automatique, quel mode doit être configuré sur S2 pour établir l’EtherChannel ?",
          m: false,
          i: "2022-06-27_121749.jpg",
          o: ["off", "auto", "on", "desirable"],
          a: [3],
          e: "PAgP se forme quand : on/on, auto/desirable, ou desirable/desirable. Pour 'auto', l'autre côté doit être 'desirable'.",
        },
        {
          c: "stp",
          q: "Ouvrez le fichier d’activité Packet Tracer. Effectuez les tâches dans les instructions relatives et puis répondez à la question. Quel ensemble de commandes de configuration émises sur le SW1 permettra de compléter avec succès la liaison EtherChannel entre le SW1 et le SW2 ?",
          m: false,
          i: "2022-06-27_114700.jpg",
          o: [
            "interface Port-channel 1 / no shutdown",
            "interface GigabitEthernet0/1 / channel-group 1 mode desirable",
            "interface GigabitEthernet0/2 / channel-group 2 mode desirable",
            "interface GigabitEthernet0/1 / no shutdown",
          ],
          a: [1],
          e: "Il manque la commande 'channel-group 1 mode desirable' sur GigabitEthernet0/1 pour compléter la configuration EtherChannel.",
        },
        {
          c: "stp",
          q: "Quelle est l’une des caractéristiques du protocole Spanning Tree ?",
          m: false,
          o: [
            "Il empêche la propagation des trames de diffusion de couche 2.",
            "Il permet de détecter les informations relatives à un appareil Cisco contigu.",
            "Il est activé par défaut sur les commutateurs Cisco.",
            "Il implémente un mécanisme TTL qui fonctionne sur la couche 2.",
          ],
          a: [2],
          e: "Le STP est activé par défaut sur les commutateurs Cisco. Les trames de couche 2 n'ont pas de TTL, c'est précisément pourquoi le STP est nécessaire.",
        },
        {
          c: "stp",
          q: "Quel protocole fournit jusqu’à 16 instances de RSTP, combine de nombreux VLAN avec la même topologie physique et logique en une instance RSTP commune, et fournit une prise en charge de PortFast, une protection BPDU, un filtre BPDU, une protection de racine et une protection de boucle ?",
          m: false,
          o: ["STP", "PVST+", "Rapid PVST+", "MST"],
          a: [3],
          e: "MST est l'implémentation Cisco de MSTP (IEEE 802.1s) : jusqu'à 16 instances RSTP, combinant plusieurs VLAN dans une instance commune.",
        },
        {
          c: "stp",
          q: "Quelle valeur est utilisée pour déterminer le port d’un pont non racine qui deviendra un port racine dans un réseau STP ?",
          m: false,
          o: [
            "Le coût du chemin",
            "L'adresse MAC la plus élevée de tous les ports du commutateur",
            "La plus petite adresse MAC de tous les ports du commutateur",
            "Le nombre de révisions VTP",
          ],
          a: [0],
          e: "Le port racine est le port dont le coût du chemin vers le pont racine est le plus faible.",
        },
        {
          c: "stp",
          q: "Quel rôle de port affecté au port de commutation présente le coût le plus faible pour accéder au pont racine ?",
          m: false,
          o: [
            "port racine",
            "port désactivé",
            "port non désigné",
            "port désigné",
          ],
          a: [0],
          e: "Le port racine est le port dont le coût d'accès au pont racine est minimal.",
        },
        {
          c: "stp",
          q: "Le réseau d’une petite entreprise compte six commutateurs de couche 2 interconnectés. Actuellement tous les commutateurs utilisent la valeur de priorité de pont par défaut. Quelle valeur permet de configurer la priorité de pont de l’un des commutateurs de sorte qu’il devienne le pont racine dans cette conception ?",
          m: false,
          o: ["1", "28672", "32768", "34816", "61440"],
          a: [1],
          e: "La valeur par défaut est 32768. Les valeurs valides sont des multiples de 4096. 28672 < 32768 est valide et permettra au commutateur de devenir pont racine.",
        },
        {
          c: "stp",
          q: "Examinez l’illustration. L’administrateur a essayé de créer un EtherChannel entre S1 et les deux autres commutateurs par le biais des commandes illustrées, mais sans succès. Quel est le problème ?",
          m: false,
          i: "2022-06-27_163320.jpg",
          o: [
            "Le trafic ne peut pas être envoyé à deux commutateurs différents, sauf entre un serveur et un commutateur.",
            "Le trafic ne peut pas être envoyé à deux commutateurs différents via la même liaison EtherChannel.",
            "Cela nécessite des interfaces Gigabit Ethernet.",
            "Cela nécessite des commutateurs de couche 3.",
          ],
          a: [1],
          e: "Une liaison EtherChannel ne peut être créée qu'entre DEUX équipements. Impossible d'envoyer vers deux commutateurs différents via la même liaison EtherChannel.",
        },
        {
          c: "stp",
          q: "Lorsqu’EtherChannel est configuré, quel mode permet de forcer une interface vers un canal de port sans échange de paquets de protocole d’agrégation ?",
          m: false,
          o: ["desirable", "active", "on", "auto"],
          a: [2],
          e: "Le mode 'on' force une interface dans un EtherChannel sans échange de paquets PAgP ni LACP.",
        },
        {
          c: "stp",
          q: "Quelle est la description correcte d’une caractéristique d’EtherChannel ?",
          m: false,
          o: [
            "Résultat de la combinaison de plusieurs liaisons physiques en une seule liaison logique entre deux commutateurs.",
            "Il peut regrouper des types mixtes de liaisons 100 Mbit/s et 1 Gbit/s.",
            "Il est constitué de plusieurs liaisons parallèles entre un commutateur et un routeur.",
            "Il peut combiner jusqu'à 4 liaisons physiques.",
          ],
          a: [0],
          e: "EtherChannel combine plusieurs liaisons physiques du même type en une seule liaison logique. Jusqu'à 8 ports Ethernet peuvent être regroupés.",
        },
        {
          c: "stp",
          q: "Un administrateur réseau configure une liaison EtherChannel entre les commutateurs SW1 et SW2 à l’aide de la commande SW1(config-if-range)# channel-group 1 mode passive . Quelle commande doit être utilisée sur SW2 pour activer cet EtherChannel ?",
          m: false,
          o: [
            "channel-group 1 mode on",
            "channel-group 1 mode active",
            "channel-group 1 mode desirable",
            "channel-group 1 mode passive",
          ],
          a: [1],
          e: "Combinaisons LACP valides : on/on, active/active, passive/active. 'passive' sur SW1 nécessite 'active' sur SW2.",
        },
        {
          c: "stp",
          q: "Quelle technologie correspond à une norme de protocole ouvert permettant le regroupement automatique de ports physiques sous forme d’une liaison logique unique ?",
          m: false,
          o: ["Protocole PPP multiliaison", "DTP", "PAgP", "LACP"],
          a: [3],
          e: "LACP (IEEE 802.3ad) est le protocole standard ouvert pour le regroupement de ports. PAgP est l'équivalent propriétaire Cisco.",
        },
        {
          c: "stp",
          q: "Reportez-vous à l’illustration. Un administrateur réseau a exécuté la commande show etherchannel summary sur le commutateur S1. Quelle conclusion pouvez-vous tirer ?",
          m: false,
          i: "2022-06-27_163438.jpg",
          o: [
            "Les ports FastEthernet Fa0/1, Fa0/2 et Fa0/3 ne rejoignent pas l'EtherChannel.",
            "L'EtherChannel est suspendu.",
            "Le protocole PAgP est mal configuré.",
            "L'EtherChannel n'est pas opérationnel.",
          ],
          a: [3],
          e: "Le statut (SD) indique un EtherChannel de couche 2 avec statut D = 'down'. L'EtherChannel n'est pas opérationnel.",
        },
        {
          c: "stp",
          q: "Quels sont les deux avantages de l’utilisation de LACP? (Choisissez deux propositions.)",
          m: true,
          o: [
            "Il élimine la nécessité de configurer les interfaces de jonction lors du déploiement de VLAN.",
            "LACP permet de combiner Fast Ethernet et Gigabit Ethernet dans un seul EtherChannel.",
            "Il fournit un environnement simulé pour tester l'agrégation de liens.",
            "Il permet l'utilisation de périphériques multifournisseurs.",
            "Il permet aux commutateurs directement connectés de négocier une liaison EtherChannel.",
            "Il réduit la quantité de configuration nécessaire sur un commutateur.",
          ],
          a: [3, 4],
          e: "LACP permet aux commutateurs multifournisseurs de négocier un EtherChannel en détectant les configurations de chaque côté.",
        },
        {
          c: "stp",
          q: "Quels sont deux avantages de l’EtherChannel ? (Choisissez deux réponses.)",
          m: true,
          o: [
            "La configuration de l'interface EtherChannel assure une cohérence lors de la configuration des liaisons physiques.",
            "L'équilibrage de la charge entre les liaisons EtherChannel différentes.",
            "Le STP assure la redondance en faisant passer les interfaces défaillantes à l'état d'acheminement.",
            "Le STP voit les liaisons physiques d'un EtherChannel comme une connexion logique unique.",
            "L'EtherChannel utilise des liaisons physiques mises à niveau pour fournir davantage de bande passante.",
          ],
          a: [0, 3],
          e: "La configuration d'une interface logique garantit la cohérence des liaisons physiques. Le STP voit l'EtherChannel comme une seule connexion logique.",
        },
        {
          c: "stp",
          q: "Un commutateur est configuré pour exécuter STP. Quel terme décrit un champ dont la valeur par défaut est 32 768 et est le facteur déterminant initial lors de l’élection d’un pont racine?",
          m: false,
          o: ["Priorité du pont", "BPDUs", "ID de pont", "ID système étendu"],
          a: [0],
          e: "La priorité du pont a une valeur par défaut de 32768 et est le premier critère de sélection du pont racine.",
        },
        {
          c: "stp",
          q: "Citez deux méthodes d’équilibrage de la charge dans la technologie EtherChannel. (Choisissez deux réponses.)",
          m: true,
          o: [
            "La combinaison du port et d'une adresse IP source/destination",
            "La combinaison d'une adresse IP et MAC source/destination",
            "Port source vers port de destination",
            "Adresse MAC source vers adresse MAC de destination",
            "Adresse IP source vers adresse IP de destination",
          ],
          a: [3, 4],
          e: "Les méthodes incluent l'adresse MAC source/destination ou l'adresse IP source/destination sur les liaisons physiques.",
        },
        {
          c: "stp",
          q: "Un commutateur est configuré pour exécuter STP. Quel terme décrit le point de référence pour tous les calculs de chemin?",
          m: false,
          o: ["pont racine", "désactivé", "port désigné", "port racine"],
          a: [0],
          e: "Le pont racine est le point de référence central pour tous les calculs de chemin dans le protocole STP.",
        },
        {
          c: "stp",
          q: "Quel standard Spanning Tree prend uniquement en charge un pont racine de sorte que le trafic de tous les VLAN passe par le même chemin ?",
          m: false,
          o: ["MST", "802.1D", "Rapid PVST", "PVST+"],
          a: [1],
          e: "802.1D est le standard STP initial qui n'accepte qu'un seul pont racine pour tous les VLAN.",
        },
        {
          c: "stp",
          q: "Un commutateur est configuré pour exécuter STP. Quel terme décrit un port non racine autorisé à transférer le trafic sur le réseau?",
          m: false,
          o: ["port désigné", "port racine", "désactivé", "port alternatif"],
          a: [0],
          e: "Le port désigné est un port en état de transmission (forwarding) autorisé à transférer le trafic.",
        },
        {
          c: "stp",
          q: "Un commutateur est configuré pour exécuter STP. Quel terme décrit le port de commutateur le plus proche, en termes de coût global, du pont racine?",
          m: false,
          o: ["port alternatif", "désactivé", "port racine", "port désigné"],
          a: [2],
          e: "Le port racine est le port sur un commutateur non racine qui offre le chemin à coût le plus faible vers le pont racine.",
        },
];
