const QUESTIONS_1_4 = [
  {
    c: "vlan",
    q: "Quelle commande est utilisée pour définir la variable d'environnement BOOT ?",
    m: false,
    o: ["config-register", "confreg", "boot loader", "boot system"],
    a: [3],
    e: "La commande boot system permet de définir la variable d'environnement BOOT qui indique où trouver l'image IOS.",
  },
  {
    c: "vlan",
    q: "Qu'est-ce qu'un commutateur utilise pour localiser et charger l'image IOS ?",
    m: false,
    o: [
      "Fichier d'image IOS",
      "Variable d'environnement BOOT",
      "NVRAM",
      "Configuration initiale",
      "POST",
    ],
    a: [1],
    e: "La variable d'environnement BOOT indique au commutateur où trouver l'image IOS à charger.",
  },
  {
    c: "vlan",
    q: "Quel protocole renforce la sécurité des connexions à distance ?",
    m: false,
    o: ["SSH", "HTTP", "NetBEUI", "FTP", "POP"],
    a: [0],
    e: "SSH (Secure Shell) chiffre les communications et renforce la sécurité des accès à distance, contrairement à Telnet.",
  },
  {
    c: "vlan",
    q: "Quelle caractéristique décrit la commutation cut-through ?",
    m: false,
    o: [
      "Seules les trames sortantes subissent une vérification d'erreurs",
      "Les fragments exempts d'erreurs sont transmis avec une faible latence",
      "Les trames sont transmises sans aucune vérification d'erreurs",
      "La mise en mémoire tampon permet de prendre en charge différentes vitesses Ethernet",
    ],
    a: [1],
    e: "La commutation cut-through (sans fragmentation) transmet les fragments exempts d'erreurs avec une faible latence en ne lisant que l'adresse MAC destination avant de transmettre.",
  },
  {
    c: "vlan",
    q: "Quelle est la différence entre un concentrateur et un commutateur LAN ?",
    m: false,
    o: [
      "Un concentrateur divise les domaines de collision",
      "Chaque port de concentrateur est un domaine de collision; chaque port de commutateur est un domaine de diffusion",
      "Un concentrateur étend le domaine de collision; un commutateur divise les domaines de collision",
      "Un concentrateur transmet des cadres; un commutateur transmet des paquets",
    ],
    a: [2],
    e: "Un concentrateur (hub) étend le domaine de collision car tous les ports partagent le même domaine. Un commutateur crée un domaine de collision par port.",
  },
  {
    c: "vlan",
    q: "Sur quoi un commutateur Ethernet base-t-il ses décisions de transfert de trames ?",
    m: false,
    o: [
      "Transfert basé sur l'adresse MAC source et les mappages de ports dans la table d'adresses MAC",
      "Les trames avec des adresses MAC inconnues sont abandonnées",
      "Les tables d'adresses MAC sont créées à partir de l'adresse de destination",
      "Les trames de monodiffusion sont toujours transmises à tous les ports",
    ],
    a: [0],
    e: "Le commutateur consulte sa table d'adresses MAC pour associer l'adresse MAC destination au port correspondant et transférer la trame.",
  },
  {
    c: "vlan",
    q: "Quel est l'impact des tampons de trame d'un commutateur sur les performances du réseau ?",
    m: false,
    o: [
      "Ils conservent les données lors d'une collision jusqu'à la reprise de la transmission",
      "Ils stockent les trames reçues, ce qui évite le rejet prématuré de trames",
      "Ils fournissent une vérification des erreurs",
      "Ils fournissent une mémoire supplémentaire par port",
    ],
    a: [1],
    e: "Les tampons de trame permettent de stocker temporairement les trames reçues, évitant ainsi leur rejet prématuré lors des pics de trafic.",
  },
  {
    c: "vlan",
    q: "Quelle caractéristique d'un commutateur permet de garder le trafic local et d'éviter la congestion ?",
    m: false,
    o: [
      "Grands tampons de trame",
      "Commutation interne rapide",
      "Vitesse de port rapide",
      "Nombre élevé de ports",
    ],
    a: [3],
    e: "Un commutateur avec un nombre élevé de ports permet de segmenter le réseau en plus de domaines de collision, gardant ainsi le trafic local.",
  },
  {
    c: "vlan",
    q: "Examinez l'illustration. Lorsqu'un commutateur traite une trame entrante, dans quel ordre effectue-t-il les étapes suivantes ?",
    m: false,
    o: [
      "Vérifier l'@ MAC source dans la table → Ajouter si absente → Examiner l'@ MAC destination → Transférer par le port correspondant ou inonder tous les ports",
      "Examiner l'@ MAC destination → Vérifier l'@ MAC source → Ajouter si absente → Transférer ou inonder",
      "Inonder tous les ports → Vérifier l'@ MAC source → Examiner l'@ MAC destination → Ajouter si absente",
      "Ajouter l'@ MAC source → Vérifier l'@ MAC destination → Examiner les ports → Transférer ou inonder",
    ],
    a: [0],
    e: "Le commutateur vérifie d'abord l'@ MAC source, l'ajoute à sa table si absente, puis examine l'@ MAC destination pour transférer ou inonder.",
  },
  {
    c: "vlan",
    q: "Quelle méthode de commutation garantit la transmission d'une trame sans erreur en effectuant une vérification FCS complète ?",
    m: false,
    o: [
      "Coupure (Cut-Through)",
      "FCS",
      "Sans fragmentation (Fragment-Free)",
      "Stockage et transmission (Store-and-Forward)",
    ],
    a: [3],
    e: "La méthode Store-and-Forward stocke la trame entière et vérifie le FCS avant de la transmettre, garantissant ainsi l'absence d'erreurs.",
  },
  {
    c: "vlan",
    q: "Quelle commande supprime uniquement le VLAN 100 d'un commutateur ?",
    m: false,
    o: [
      "Switch(config-if)# no switchport access vlan 100",
      "Switch(config-if)# no switchport trunk allowed vlan 100",
      "Switch# delete flash:vlan.dat",
      "Switch(config)# no vlan 100",
    ],
    a: [3],
    e: "La commande no vlan 100 en mode de configuration globale supprime uniquement le VLAN 100. delete flash:vlan.dat supprimerait tous les VLAN.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Pourquoi les interfaces Gi0/1 et Gi0/2 n'apparaissent-elles pas dans le résultat de la commande show vlan brief ?",
    m: false,
    o: [
      "Les VLAN natifs ne correspondent pas entre les deux commutateurs",
      "Les interfaces ont été arrêtées administrativement",
      "Les interfaces sont configurées comme des interfaces d'agrégation (trunk)",
      "Aucun support physique n'est connecté aux interfaces",
    ],
    a: [2],
    e: "Les ports trunk n'apparaissent pas dans show vlan brief car ils ne sont pas attribués à un VLAN spécifique — ils transportent le trafic de plusieurs VLAN.",
  },
  {
    c: "vlan",
    q: "Une trame Ethernet de diffusion est envoyée depuis un hôte dans le VLAN 20. Qui reçoit cette trame ?",
    m: false,
    o: [
      "Tous les périphériques de tous les VLAN",
      "Les périphériques du VLAN 20 et du VLAN de gestion",
      "Seuls les périphériques du VLAN 20",
      "Seuls les périphériques du commutateur local",
    ],
    a: [2],
    e: "Les VLAN segmentent les domaines de diffusion. Une diffusion dans le VLAN 20 n'est reçue que par les périphériques appartenant au VLAN 20.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Les stations de SW1 ne peuvent pas envoyer de trafic vers SW2. Quelle action résoudrait ce problème ?",
    m: false,
    o: [
      "Autoriser le VLAN 20 sur la liaison agrégée entre SW1 et SW2",
      "Configurer les stations de SW2 sur le VLAN natif",
      "Configurer les stations de SW1 sur le VLAN par défaut",
      "Activer le protocole DTP des deux côtés de la liaison",
    ],
    a: [0],
    e: "Pour que le trafic du VLAN 20 traverse la liaison trunk entre SW1 et SW2, le VLAN 20 doit être autorisé sur cette liaison.",
  },
  {
    c: "vlan",
    q: "Associez l'étiquette IEEE 802.1Q à la description correspondante.",
    m: false,
    o: [
      "Type (TPID)=2 octets, Priorité utilisateur=3 bits, CFI=1 bit, VID=12 bits (supporte jusqu'à 4096 ID VLAN)",
      "Type (TPID)=4 octets, Priorité utilisateur=2 bits, CFI=2 bits, VID=10 bits",
      "Type (TPID)=2 octets, Priorité utilisateur=1 bit, CFI=3 bits, VID=8 bits",
      "Type (TPID)=1 octet, Priorité utilisateur=4 bits, CFI=2 bits, VID=16 bits",
    ],
    a: [0],
    e: "L'étiquette 802.1Q contient : TPID (2 octets), priorité utilisateur (3 bits), CFI (1 bit) et VID sur 12 bits permettant 4096 VLAN.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Selon les bonnes pratiques Cisco, quel mode doit être configuré pour le port G0/1 connecté à un autre commutateur ?",
    m: false,
    o: ["trunk", "accès", "auto", "desirable"],
    a: [0],
    e: "Selon les bonnes pratiques Cisco, les liaisons entre commutateurs doivent être configurées manuellement en mode trunk plutôt que de laisser la négociation automatique.",
  },
  {
    c: "vlan",
    q: "Quelle commande affiche le type d'encapsulation, l'accès et l'ID de VLAN voix d'une interface ?",
    m: false,
    o: [
      "show interfaces trunk",
      "show vlan brief",
      "show mac address-table interface Fa0/1",
      "show interfaces Fa0/1 switchport",
    ],
    a: [3],
    e: "La commande show interfaces [interface] switchport affiche les détails de configuration du port, notamment le type d'encapsulation et les VLAN attribués.",
  },
  {
    c: "vlan",
    q: "Quelles sont les quatre étapes nécessaires pour configurer un VLAN voix sur un commutateur ? (Choisissez quatre réponses.)",
    m: true,
    o: [
      "Configurer le port de commutation en mode accès",
      "Ajouter le VLAN voix",
      "Configurer des sous-interfaces sur l'interface",
      "Configurer l'interface en mode trunk 802.1Q",
      "Activer spanning-tree PortFast sur le port",
      "Assigner un VLAN de données au port",
      "S'assurer que le trafic voix est approuvé avec priorité CoS",
      "Assigner un VLAN voix au port",
    ],
    a: [0, 1, 4, 5],
    e: "Pour configurer un VLAN voix : mode accès, ajouter le VLAN voix, activer PortFast (pour la convergence rapide) et assigner le VLAN données.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelle est la cause de l'erreur de configuration du routage inter-VLAN de CiscoVille ?",
    m: false,
    o: [
      "L'interface gig0/0 ne prend pas en charge le routage inter-VLAN",
      "L'adresse IP de CiscoVille est incorrecte",
      "La commande encapsulation dot1Q 20 n'est pas configurée sur la sous-interface",
      "La commande no shutdown n'est pas configurée sur la sous-interface",
    ],
    a: [2],
    e: "Pour le routage inter-VLAN avec router-on-a-stick, chaque sous-interface doit avoir la commande encapsulation dot1Q [VLAN-ID] pour identifier le VLAN.",
  },
  {
    c: "vlan",
    q: "Quels sont les deux inconvénients du routage inter-VLAN de type Router-on-a-Stick ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Nécessite des sous-interfaces sur les mêmes sous-réseaux",
      "Un routeur dédié est nécessaire",
      "Plusieurs sous-interfaces peuvent affecter le débit du trafic",
      "Nécessite plusieurs interfaces physiques sur le routeur",
      "Des interfaces SVI multiples sont nécessaires",
    ],
    a: [1, 2],
    e: "Router-on-a-stick nécessite un routeur dédié et un seul lien physique peut devenir un goulot d'étranglement avec de nombreuses sous-interfaces.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelles sont les erreurs dans la configuration de l'interface Gi1/1 du commutateur ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "La négociation d'agrégation est activée (DTP actif)",
      "L'interface est configurée en mode agrégation alors qu'elle devrait être en mode accès",
      "L'interface Gi1/1 est dans le VLAN par défaut",
      "Le protocole d'encapsulation d'agrégation est mal configuré",
      "Le VLAN voix n'est pas attribué",
    ],
    a: [0, 1],
    e: "Selon les bonnes pratiques, les ports d'accès ne doivent pas être en mode trunk et la négociation DTP doit être désactivée pour éviter les attaques.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelle est la cause pour laquelle PC2 ne peut pas communiquer avec PC1 ?",
    m: false,
    o: [
      "La commande encapsulation dot1Q 5 indique un mauvais numéro de VLAN",
      "L'interface GigabitEthernet0/0.5 n'est pas correctement saisie",
      "Aucune adresse IP n'est configurée sur l'interface physique Gi0/0",
      "L'interface Gi0/0 n'est pas configurée en port agrégé",
      "La commande no shutdown n'a pas été exécutée sur les sous-interfaces",
    ],
    a: [4],
    e: "Les sous-interfaces sont désactivées par défaut. La commande no shutdown doit être exécutée sur chaque sous-interface pour l'activer.",
  },
  {
    c: "vlan",
    q: "Quelles sont les deux caractéristiques d'un port routé sur un commutateur de couche 3 ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Il prend en charge le trunking",
      "Il est généralement utilisé comme liaison WAN ou point-à-point",
      "Aucune adresse IP ne peut lui être attribuée",
      "Il n'est pas attribué à un VLAN spécifique",
    ],
    a: [1, 3],
    e: "Un port routé sur un commutateur L3 n'est pas associé à un VLAN et est utilisé comme interface de couche 3 pour le routage (liaisons WAN, point-à-point).",
  },
  {
    c: "vlan",
    q: "Quel est l'effet de la commande BranchSw(config-if)# shutdown ?",
    m: false,
    o: [
      "Mettre à jour la table d'adresses MAC",
      "Enregistrer la configuration active",
      "Activer une interface virtuelle ou physique",
      "Enregistrer la configuration en NVRAM",
      "Désactiver une interface virtuelle ou physique",
    ],
    a: [4],
    e: "La commande shutdown désactive l'interface. La commande no shutdown est utilisée pour activer l'interface.",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN correspond initialement au VLAN de gestion sur un commutateur Cisco ?",
    m: false,
    o: ["VLAN de gestion", "VLAN par défaut", "VLAN de données", "VLAN natif"],
    a: [1],
    e: "Par défaut, le VLAN 1 est à la fois le VLAN par défaut, le VLAN natif et le VLAN de gestion. Il est recommandé de modifier le VLAN de gestion.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelle commande supplémentaire est nécessaire pour activer l'interface série de R1 ?",
    m: false,
    o: ["clockrate 128000", "end", "IPv6 enable", "no shutdown"],
    a: [3],
    e: "Les interfaces de routeur sont désactivées par défaut. La commande no shutdown est nécessaire pour activer l'interface.",
  },
  {
    c: "vlan",
    q: "Quelle modification de configuration permettrait d'autoriser SSH tout en interdisant Telnet sur les lignes VTY ?",
    m: false,
    o: [
      "Reconfigurer la clé RSA",
      "Modifier la commande transport input",
      "Configurer SSH sur une ligne VTY différente",
      "Utiliser SSH version 1",
    ],
    a: [1],
    e: "La commande transport input ssh (sur les lignes VTY) autorise uniquement SSH et interdit Telnet.",
  },
  {
    c: "vlan",
    q: "Quelle solution réduirait la congestion du réseau et les collisions dans le réseau de l'université ?",
    m: false,
    o: [
      "Un routeur avec trois ports Ethernet",
      "Un pare-feu connecté à deux fournisseurs de services",
      "Un commutateur à haute densité de ports",
      "Un routeur avec deux ports Ethernet",
    ],
    a: [2],
    e: "Un commutateur à haute densité de ports segmente le réseau en nombreux domaines de collision, réduisant ainsi la congestion.",
  },
  {
    c: "vlan",
    q: "Quels sont les deux énoncés corrects concernant le routage inter-VLAN avec SVI sur un commutateur multicouche ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Aucune connexion à un routeur externe n'est nécessaire",
      "La commutation de paquets est plus rapide avec les SVI qu'avec router-on-a-stick",
      "Les interfaces virtuelles prennent en charge les sous-interfaces",
      "Les SVI peuvent être regroupés en EtherChannels",
      "Les SVI éliminent le besoin d'une passerelle par défaut",
    ],
    a: [0, 1],
    e: "Avec un commutateur L3 et des SVI, aucun routeur externe n'est nécessaire et la commutation est plus rapide car elle se fait en matériel (ASIC).",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quel est le rôle du paramètre manquant représenté par le point d'interrogation dans la commande ?",
    m: false,
    o: [
      "Il identifie le numéro de VLAN",
      "Il identifie la sous-interface",
      "Il identifie le type d'encapsulation utilisé",
      "Il identifie le nombre d'hôtes autorisés",
      "Il identifie le numéro du VLAN natif",
    ],
    a: [2],
    e: "Dans la commande encapsulation [?] [VLAN-ID], le paramètre manquant est le type d'encapsulation (dot1Q pour 802.1Q).",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN indique les trames non étiquetées reçues sur un port agrégé ?",
    m: false,
    o: ["données", "par défaut", "natif", "management"],
    a: [2],
    e: "Le VLAN natif est le VLAN pour lequel les trames ne sont pas étiquetées sur une liaison trunk 802.1Q.",
  },
  {
    c: "vlan",
    q: "Qu'affiche le résultat de la commande show vlan brief ?",
    m: false,
    o: [
      "L'affectation VLAN et les périphériques avec leur adresse MAC",
      "L'affectation VLAN et le type d'encapsulation de trunking",
      "L'affectation VLAN et les ports de commutation appartenant à chaque VLAN",
      "L'affectation VLAN et le réseau du VLAN natif",
    ],
    a: [2],
    e: "show vlan brief affiche pour chaque VLAN : son ID, son nom, son état et les ports qui lui sont attribués.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quel message s'affiche lorsque l'utilisateur accède à 10.10.10.1 depuis le navigateur Web de PC1 ?",
    m: false,
    o: ["Serveur local", "Serveur test", "Serveur Cisco", "Serveur fichiers"],
    a: [2],
    e: "En accédant à l'adresse IP du serveur via HTTP, l'utilisateur voit le contenu de la page web hébergée, ici 'Serveur Cisco'.",
  },
  {
    c: "vlan",
    q: "Quelle commande affiche les informations sur le paramètre auto-MDIX d'une interface ?",
    m: false,
    o: [
      "show controllers",
      "show processes",
      "show interfaces",
      "show running-config",
    ],
    a: [3],
    e: "La commande show running-config affiche la configuration active incluant le paramètre mdix auto sur les interfaces concernées.",
  },
  {
    c: "vlan",
    q: "Où se produisent les collisions tardives (late collisions) selon le mode duplex configuré ?",
    m: false,
    o: [
      "Sur l'extrémité configurée en mode semi-duplex",
      "Uniquement sur les interfaces série",
      "Sur l'extrémité configurée en mode full duplex",
      "Sur les deux extrémités de la connexion",
    ],
    a: [0],
    e: "Les collisions tardives se produisent en mode semi-duplex, souvent lorsqu'il y a une incompatibilité duplex entre deux équipements.",
  },
  {
    c: "vlan",
    q: "Quel est l'impact de l'ajout d'un commutateur de couche 2 à un réseau ?",
    m: false,
    o: [
      "Augmentation de la taille du domaine de collision",
      "Augmentation du nombre de collisions",
      "Augmentation de la taille du domaine de diffusion",
      "Augmentation du nombre de trames ignorées",
    ],
    a: [2],
    e: "Un commutateur L2 ne filtre pas les diffusions. En ajoutant un commutateur, on connecte plus de périphériques au même domaine de diffusion.",
  },
  {
    c: "vlan",
    q: "Quelles informations sont ajoutées à la table de commutation lorsqu'une trame entrante est traitée ?",
    m: false,
    o: [
      "Adresse IP de destination et numéro du port entrant",
      "Adresse MAC de destination et numéro du port entrant",
      "Adresse MAC source et numéro du port entrant",
      "Adresse IP source et numéro du port entrant",
    ],
    a: [2],
    e: "Le commutateur apprend en associant l'adresse MAC SOURCE de la trame entrante au port sur lequel elle est arrivée.",
  },
  {
    c: "vlan",
    q: "Dans quels cas faut-il désactiver le protocole DTP ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Le commutateur voisin est en mode DTP dynamic auto",
      "Le commutateur voisin est en mode DTP dynamic desirable",
      "Connexion d'un commutateur Cisco à un commutateur d'un autre fournisseur",
      "Les liaisons ne doivent pas être agrégées (non-trunk)",
      "Les liaisons doivent tenter l'agrégation de manière dynamique",
    ],
    a: [2, 3],
    e: "DTP doit être désactivé lors de la connexion à des équipements non-Cisco (incompatibilité) et sur les ports qui ne doivent pas devenir des trunks.",
  },
  {
    c: "vlan",
    q: "Que se passe-t-il pour les ports d'un commutateur lorsque le VLAN auquel ils sont attribués est supprimé ?",
    m: false,
    o: [
      "Les ports sont désactivés",
      "Les ports cessent de communiquer avec tous les appareils",
      "Les ports passent automatiquement en mode Trunk",
      "Les ports sont affectés au VLAN par défaut (VLAN 1)",
    ],
    a: [3],
    e: "Lorsqu'un VLAN est supprimé, les ports qui lui étaient attribués sont automatiquement renvoyés au VLAN par défaut (VLAN 1).",
  },
  {
    c: "vlan",
    q: "Quel élément est nécessaire pour permettre la communication entre les hôtes du VLAN 15 et du VLAN 30 en utilisant la méthode router-on-a-stick ?",
    m: false,
    o: [
      "Un routeur avec deux interfaces LAN physiques",
      "Un commutateur multicouche",
      "Deux groupes de commutateurs avec des ports configurés dans les VLAN",
      "Un commutateur avec un port en ligne principale pour se connecter au routeur",
    ],
    a: [0],
    e: "Router-on-a-stick utilise un seul routeur avec deux sous-interfaces (une par VLAN). Le routeur doit avoir une interface physique connectée au commutateur en mode trunk.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelle est la cause pour laquelle les hôtes ne peuvent pas communiquer via la configuration de RT1 ?",
    m: false,
    o: [
      "Les adresses IP des sous-interfaces ne sont pas correctement associées aux VLAN correspondants",
      "Chaque sous-interface de Fa0/0 nécessite une commande no shutdown séparée",
      "Les routeurs IOS ne prennent pas en charge l'encapsulation 802.1Q",
      "Les informations d'adresses IP sont manquantes sur l'interface physique Fa0/0",
    ],
    a: [0],
    e: "Chaque sous-interface doit être configurée avec la bonne commande encapsulation dot1Q [VLAN-ID] pour traiter correctement le trafic VLAN correspondant.",
  },
  {
    c: "vlan",
    q: "Quel est l'effet de la commande BranchSw(config-if)# mdix auto ?",
    m: false,
    o: [
      "Elle ajuste automatiquement le port pour utiliser un câble direct ou croisé",
      "Elle met à jour la table d'adresses MAC",
      "Elle configure une adresse IPv6 sur l'interface physique",
      "Elle applique une adresse IPv4 à l'interface virtuelle",
      "Elle applique une adresse IPv6 à l'interface virtuelle",
    ],
    a: [0],
    e: "La fonctionnalité auto-MDIX détecte automatiquement le type de câble utilisé (direct ou croisé) et configure le port en conséquence.",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN est requis pour garantir un retard de moins de 150 ms sur le réseau ?",
    m: false,
    o: ["VLAN trunk", "VLAN souhaitable", "VLAN voix", "VLAN sécurité"],
    a: [2],
    e: "Le VLAN voix (voice VLAN) est conçu pour transporter le trafic de téléphonie IP avec une priorité élevée et un délai garanti inférieur à 150 ms.",
  },
  {
    c: "vlan",
    q: "Quelle est la caractéristique d'une interface de bouclage (loopback) IPv4 sur un routeur IOS ?",
    m: false,
    o: [
      "Une seule interface de bouclage peut être active par routeur",
      "Elle est attribuée à un port physique et connectée à d'autres périphériques",
      "C'est une interface logique interne du routeur",
      "La commande no shutdown est nécessaire pour la maintenir en état UP/UP",
    ],
    a: [2],
    e: "Une interface loopback est une interface logique virtuelle du routeur qui reste toujours active (UP) tant que le routeur fonctionne.",
  },
  {
    c: "vlan",
    q: "Quelle est la taille minimale d'une trame Ethernet valide ? Les trames inférieures à cette taille sont rejetées.",
    m: false,
    o: ["64 octets", "512 octets", "1024 octets", "1500 octets"],
    a: [0],
    e: "La taille minimale d'une trame Ethernet est de 64 octets. Les trames plus petites sont appelées runts et sont rejetées.",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN ne transporte pas le trafic de gestion, vocale et réseau spécifique ?",
    m: false,
    o: ["VLAN trunk", "VLAN sécurité", "VLAN données", "VLAN voix"],
    a: [2],
    e: "Le VLAN données est dédié au trafic utilisateur généré par les ordinateurs. Il ne doit pas transporter la voix, la gestion ou d'autres trafics spéciaux.",
  },
  {
    c: "vlan",
    q: "Quelle commande doit être utilisée sur une interface de commutateur pour activer le routage inter-VLAN via router-on-a-stick ?",
    m: false,
    o: [
      "switchport mode access",
      "no switchport",
      "switchport mode dynamic desirable",
      "switchport mode trunk",
    ],
    a: [3],
    e: "Le port du commutateur connecté au routeur doit être configuré en mode trunk pour transporter le trafic de plusieurs VLAN vers le routeur.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Combien de sous-interfaces sont créées sur le routeur ?",
    m: false,
    o: ["1", "2", "3", "4", "5"],
    a: [4],
    e: "Une sous-interface est créée pour chaque VLAN nécessitant le routage inter-VLAN. Si 5 VLAN nécessitent du routage, 5 sous-interfaces sont créées.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Combien de domaines de diffusion apparaissent dans l'illustration ?",
    m: false,
    o: ["16", "1", "55", "8", "4"],
    a: [3],
    e: "Chaque VLAN représente un domaine de diffusion distinct. Les routeurs séparent également les domaines de diffusion.",
  },
  {
    c: "vlan",
    q: "Quel est l'effet de la commande BranchSw# configure terminal ?",
    m: false,
    o: [
      "Mettre à jour la table d'adresses MAC",
      "Passer en mode de configuration globale",
      "Entrer en mode de configuration d'interface virtuelle",
      "Configurer une adresse IPv6 sur une interface physique",
      "Appliquer une adresse IPv4 à une interface virtuelle",
    ],
    a: [1],
    e: "La commande configure terminal (ou conf t) fait passer le routeur/commutateur en mode de configuration globale (config)#.",
  },
  {
    c: "vlan",
    q: "Quels sont les deux énoncés qui décrivent correctement le VLAN natif ? (Choisissez deux réponses.)",
    m: true,
    o: [
      "Le trafic du VLAN natif n'est pas étiqueté sur une liaison agrégée (trunk)",
      "Le VLAN natif fournit un identificateur commun aux deux extrémités d'une liaison agrégée",
      "Ce VLAN est nécessaire pour la gestion à distance d'un commutateur",
      "Ce VLAN transporte le trafic utilisateur, d'où son appellation VLAN par défaut",
      "Le trafic à haute priorité, comme la voix, utilise le VLAN natif",
    ],
    a: [0, 1],
    e: "Le VLAN natif (par défaut VLAN 1) transmet les trames sans étiquette 802.1Q et doit être identique des deux côtés d'un trunk.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelle conclusion peut-on tirer de l'affichage des interfaces trunk ?",
    m: false,
    o: [
      "L'interface G0/2 n'est pas configurée en port trunk",
      "Le VLAN 20 n'est pas créé sur le commutateur",
      "Le mode DTP est défini sur dynamic auto sur l'interface G0/1",
      "L'encapsulation de l'interface G0/1 est incorrecte",
    ],
    a: [0],
    e: "Si G0/2 n'apparaît pas dans le résultat de show interfaces trunk, c'est qu'elle n'est pas configurée en mode trunk.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quel est le problème dans la configuration du port Fa0/20 de SW3 ?",
    m: false,
    o: [
      "La commande d'attribution du VLAN voix au port est incorrecte",
      "La commande mls qos trust cos est associée au mauvais VLAN",
      "La configuration ne présente aucune erreur",
      "Un seul VLAN peut être assigné à l'interface Fa0/20",
    ],
    a: [0],
    e: "Pour configurer un VLAN voix, la syntaxe correcte est switchport voice vlan [ID]. Une erreur de syntaxe empêcherait l'attribution correcte.",
  },
  {
    c: "vlan",
    q: "Quel composant d'un commutateur réduit le traitement des paquets par le CPU ?",
    m: false,
    o: [
      "Des processeurs doubles",
      "De grandes mémoires tampons",
      "ASIC (Application-Specific Integrated Circuit)",
      "RAM pour stockage et transmission",
    ],
    a: [2],
    e: "Les ASIC sont des circuits intégrés spécialisés qui effectuent la commutation en matériel, réduisant considérablement la charge du CPU.",
  },
  {
    c: "vlan",
    q: "Associez chaque mode DTP à la fonction correspondante.",
    m: false,
    o: [
      "Dynamic auto=attente passive de l'agrégation, Nonegotiate=configuration manuelle sans négociation, Dynamic desirable=tentative active de conversion en trunk, Trunk=mode permanent d'agrégation",
      "Dynamic auto=tentative active, Nonegotiate=mode permanent, Dynamic desirable=attente passive, Trunk=configuration manuelle",
      "Dynamic auto=mode permanent, Nonegotiate=tentative active, Dynamic desirable=configuration manuelle, Trunk=attente passive",
      "Dynamic auto=configuration manuelle, Nonegotiate=attente passive, Dynamic desirable=mode permanent, Trunk=tentative active",
    ],
    a: [0],
    e: "DTP : auto=passif, desirable=actif, trunk=permanent, nonegotiate=pas de négociation DTP (port configuré manuellement en trunk ou access).",
  },
  {
    c: "vlan",
    q: "Quel type de port est requis sur un commutateur pour que les hôtes d'un VLAN accèdent au routeur dans une configuration router-on-a-stick ?",
    m: false,
    o: [
      "Interface SVI",
      "Port agrégé (trunk)",
      "Port routé",
      "Port d'accès",
    ],
    a: [3],
    e: "Les hôtes finaux sont connectés à des ports d'accès (access) configurés dans leur VLAN. Seul le port vers le routeur doit être en mode trunk.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Quelle est l'erreur la plus probable dans la configuration router-on-a-stick affichée ?",
    m: false,
    o: [
      "Adresse IP manquante sur l'interface physique Gigabit Ethernet 0/0",
      "Adresse IP incorrecte configurée sur la sous-interface Gigabit Ethernet 0/0.30",
      "Commande no shutdown manquante sur les sous-interfaces",
      "Mauvais VLAN configuré sur la sous-interface GigabitEthernet 0/0.45",
    ],
    a: [1],
    e: "Une mauvaise adresse IP sur une sous-interface empêcherait les hôtes du VLAN correspondant d'utiliser cette sous-interface comme passerelle.",
  },
  {
    c: "vlan",
    q: "Quel est l'effet de la commande BranchSw(config-if)# exit ?",
    m: false,
    o: [
      "Elle retourne en mode de configuration globale",
      "Elle repasse en mode EXEC privilégié",
      "Elle entre en mode utilisateur",
      "Elle configure la passerelle par défaut du commutateur",
      "Elle enregistre la configuration active",
    ],
    a: [0],
    e: "La commande exit en mode de configuration d'interface retourne au mode de configuration globale (config)#.",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN est utilisé pour séparer le réseau en groupes selon les utilisateurs et les appareils ?",
    m: false,
    o: ["VLAN natif", "VLAN données", "VLAN voix", "VLAN gestion"],
    a: [1],
    e: "Le VLAN données (ou VLAN utilisateur) est conçu pour segmenter le réseau en groupes logiques d'utilisateurs ou de périphériques.",
  },
  {
    c: "vlan",
    q: "Après quelle étape de la séquence de démarrage le chargeur de démarrage (boot loader) prend-il le contrôle ?",
    m: false,
    o: [
      "Après l'exécution du POST",
      "Après l'initialisation du CPU",
      "Après l'initialisation du système de fichiers flash",
      "Après la localisation de l'image IOS",
    ],
    a: [1],
    e: "Le processus de démarrage : initialisation CPU → exécution POST → chargeur de démarrage → initialisation flash → localisation et chargement IOS.",
  },
  {
    c: "vlan",
    q: "Reportez-vous à l'illustration. Que se passe-t-il au port Fa0/11 après la commande no switchport access vlan 30 ?",
    m: false,
    o: [
      "Le port Fa0/11 est renvoyé au VLAN 1 (VLAN par défaut)",
      "Le port Fa0/11 est mis hors service",
      "Le VLAN 30 est supprimé du commutateur",
      "Un message d'erreur s'affiche",
    ],
    a: [0],
    e: "La commande no switchport access vlan retire l'attribution de VLAN personnalisée et retourne le port au VLAN par défaut (VLAN 1).",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN est configuré pour transporter le trafic réseau SSH, Telnet, HTTPS et SNMP ?",
    m: false,
    o: ["VLAN sécurité", "VLAN voix", "VLAN gestion", "VLAN trunk"],
    a: [2],
    e: "Le VLAN de gestion transporte le trafic d'administration du réseau (SSH, Telnet, SNMP, HTTPS). Il est distinct du VLAN données pour des raisons de sécurité.",
  },
  {
    c: "vlan",
    q: "Quel est l'effet de la commande BranchSw(config-if)# ip address 172.18.33.88 255.255.255.0 ?",
    m: false,
    o: [
      "Configure une adresse IPv6 sur l'interface physique",
      "Met à jour la table d'adresses MAC",
      "Applique une adresse IPv6 à l'interface virtuelle (SVI)",
      "Applique une adresse IPv4 à l'interface virtuelle (SVI)",
      "Active l'interface virtuelle ou physique",
    ],
    a: [3],
    e: "Cette commande attribue l'adresse IPv4 172.18.33.88/24 à l'interface SVI (interface virtuelle de commutateur) pour la gestion.",
  },
  {
    c: "vlan",
    q: "Quel type de VLAN prend en charge le trafic non marqué (untagged) sur une liaison trunk ?",
    m: false,
    o: ["VLAN natif", "VLAN sécurité", "VLAN trunk", "VLAN souhaitable"],
    a: [0],
    e: "Le VLAN natif est le seul VLAN dont les trames transitent sans étiquette 802.1Q sur un port trunk. Par défaut, c'est le VLAN 1.",
  },
];
